### ISSUE TITLE
Does this code have the option to change the Newest, Oldest, or sort by popularity?

### ISSUE THREAD

**Issue by H1R0Y4** [upbit/pixivpy#104]

**Comment by upbit** [comment]
En, `sort` parameter is missing in `illust_ranking`, we need to increase it.

Can you provide field names and values for sort parameters?

e.g.: `sort: [date_desc, date_asc]`

**Comment by H1R0Y4** [comment]
How did you find date_desc and date_asc? Looking at the url, the order of popularity is order = popular_d.
(e.g. https://www.pixiv.net/tags/水着/illustrations?order=popular_d&s_mode=s_tag)
So I set sort = 'popular_d' but it didn't work.

**Comment by H1R0Y4** [comment]
I found it. It would be nice to refer to this site.
https://slab2018.slack.com/archives/DJWTWSBL2/p1575288787004600
sort='popular_desc'
I am a premium member and I was able to sort by this.

**Comment by upbit** [comment]
Good! I will check the param later: https://github.com/akameco/pixiv-app-api

**Comment by upbit** [comment]
Not work, `illust/ranking` not take the param sort (see 592071d demo outputs)
May be we need sniffer client request to found correct params for sort rankings

**Comment by H1R0Y4** [comment]
I haven't confirmed popular_desc's behavior with illust_ranking(), but it works with search_illust().

**Comment by upbit** [comment]
Today I tried to analyze the latest version of the iOS client.
There is no official ranking function for ranking because the list content is limited
