### ISSUE TITLE
请教一下请求里面的offset参数怎么用？

### ISSUE THREAD

**Issue by mashirozx** [upbit/pixivpy#110]
比如：https://github.com/upbit/pixivpy/blob/e718dfe09f304807aaf9202d3ac37af8cf18e52b/pixivpy3/aapi.py#L179-L182

**Comment by Rinacm** [comment]
offset应该是代表第几副作品，比如每页是30张那么offset=0就是第一页,offset=30就是第二页(30-60)

**Comment by Xdynix** [comment]
@Rinacm 说得对。对于AAPI，一般不用手动设置offset，直接使用`AppPixivAPI.parse_qs`从服务器响应的`next_url`里就能提取到翻页用的参数，其中就会包括offset。

**Comment by mashirozx** [comment]
了解了，谢谢二位
