### ISSUE TITLE
关于大陆地区AppAPI的免翻墙访问支持

### ISSUE THREAD

**Issue by Liupaperbox** [upbit/pixivpy#111]
我找到了项目中的免翻墙bapi.py
但是它不起作用。。。
经过检查发现是1.0.0.1被屏蔽

**Comment by Liupaperbox** [comment]
抱歉我目前还不会使用Github,只能通过这种方式表述

**Comment by PainterPuppets** [comment]
如果你不介意的话我可以帮你提pr

**Comment by upbit** [comment]
感谢反馈，我会尽快验证下。欢迎提交相关的代码，来更通用的处理这个问题

**Comment by Liupaperbox** [comment]
写错了，应该是
`# -*- coding:utf-8 -*-

import requests
from requests_toolbelt.adapters import host_header_ssl
import time

from .aapi import AppPixivAPI


class ByPassSniApi(AppPixivAPI):

    def __init__(self, **requests_kwargs):
        """initialize requests kwargs if need be"""
        super(AppPixivAPI, self).__init__(**requests_kwargs)
        session = requests.Session()
        session.mount('https://', host_header_ssl.HostHeaderSSLAdapter())
        self.requests = session

    def require_appapi_hosts(self, hostname="app-api.pixiv.net"):
        """
        请求真实的ip地址
        """
        postUrl = 'https://dnsdblookup.com/domain/read.do?domain=%s&time=%d'%(hostname,int(time.time()))
        payloadHeader = {
                'Origin': 'https://dnsdblookup.com',
                'Referer': 'https://dnsdblookup.com',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'
                }
        response = requests.post(postUrl, headers=payloadHeader)
        ips = response.json()
        for i in ips["data"]:
            try:
                requests.get("http://"+i["ip"],timeout=3)
                self.hosts = "https://" + i["ip"]
                return None
            except Exception:
                pass
`

**Comment by Liupaperbox** [comment]
> 感谢反馈，我会尽快验证下。欢迎提交相关的代码，来更通用的处理这个问题

写错了，应该是

`# -*- coding:utf-8 -*-

import requests
from requests_toolbelt.adapters import host_header_ssl
import time

from .aapi import AppPixivAPI


class ByPassSniApi(AppPixivAPI):

    def __init__(self, **requests_kwargs):
        """initialize requests kwargs if need be"""
        super(AppPixivAPI, self).__init__(**requests_kwargs)
        session = requests.Session()
        session.mount('https://', host_header_ssl.HostHeaderSSLAdapter())
        self.requests = session

    def require_appapi_hosts(self, hostname="app-api.pixiv.net"):
        """
        请求真实的ip地址
        """
        postUrl = 'https://dnsdblookup.com/domain/read.do?domain=%s&time=%d'%(hostname,int(time.time()))
        payloadHeader = {
                'Origin': 'https://dnsdblookup.com',
                'Referer': 'https://dnsdblookup.com',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'
                }
        response = requests.post(postUrl, headers=payloadHeader)
        ips = response.json()
        for i in ips["data"]:
            try:
                requests.get("http://"+i["ip"],timeout=3)
                self.hosts = "https://" + i["ip"]
                return None
            except Exception:
                pass
`

**Comment by upbit** [comment]
这里讨论 #112 吧。几个问题：

-----------------------------------

> @upbit 代码请使用AutoPEP8等工具，进行格式化。过长的代码行(单行超过120字符)，可以考虑折叠
>
> @upbit 另一个建议：tools.ipip.net/dns.php返回的内容比较复杂，可以考虑使用返回json的A记录查询接口，比如whois.com的接口，方便解析结果：
>
> ```
> $ curl "https://dig.whois.com.au/digresult/a/app-api.pixiv.net"
> [{"ttl":22,"type":1,"class":1,"name":"app-api.pixiv.net","address":"210.140.131.223"},{"ttl":22,"type":1,"class":1,"name":"app-api.pixiv.net","address":"210.140.131.225"},{"ttl":22,"type":1,"class":1,"name":"app-api.pixiv.net","address":"210.140.131.220"}]
> ```

**Comment by upbit** [comment]
另外，从深圳电信看，`1.0.0.1`还是通的。能提供下你的网络类型吗？

```
PING 1.0.0.1 (1.0.0.1): 56 data bytes
64 bytes from 1.0.0.1: icmp_seq=0 ttl=52 time=12.064 ms
64 bytes from 1.0.0.1: icmp_seq=1 ttl=52 time=9.706 ms
^C
--- 1.0.0.1 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 9.706/10.885/12.064/1.179 ms
```

**Comment by Rinacm** [comment]
> 另外，从深圳电信看，`1.0.0.1`还是通的。能提供下你的网络类型吗？@Liupaperbox
> 
> ```
> PING 1.0.0.1 (1.0.0.1): 56 data bytes
> 64 bytes from 1.0.0.1: icmp_seq=0 ttl=52 time=12.064 ms
> 64 bytes from 1.0.0.1: icmp_seq=1 ttl=52 time=9.706 ms
> ^C
> --- 1.0.0.1 ping statistics ---
> 2 packets transmitted, 2 packets received, 0.0% packet loss
> round-trip min/avg/max/stddev = 9.706/10.885/12.064/1.179 ms
> ```

河南联通1.0.0.1也是可用的，看到这篇issue我还专门去试了试

**Comment by Liupaperbox** [comment]
确实1.0.0.1可以Ping通，但是无法访问啊
`ConnectionError: HTTPSConnectionPool(host='1.0.0.1', port=443): Max retries exceeded with url: /dns-query?ct=application/dns-json&name=app-api.pixiv.net&type=A&do=false&cd=false (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F85C9CCAC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))`

**Comment by upbit** [comment]
新年快乐 😄。是我没有说清楚，不止是ping，https也试过可以访问（说明可能不是所有出口，都设置了屏蔽）

```bash
$ curl -i "https://1.0.0.1/dns-query?ct=application/dns-json&name=app-api.pixiv.net&type=A&do=false&cd=false"do=false&cd
HTTP/1.1 200 OK
Date: Sat, 25 Jan 2020 01:47:08 GMT
Content-Type: application/dns-json
Content-Length: 382
Connection: keep-alive
Access-Control-Allow-Origin: *
cache-control: max-age=118
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 55a693d2c951d1db-HKG

{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": false,"CD": false,"Question":[{"name": "app-api.pixiv.net.", "type": 1}],"Answer":[{"name": "app-api.pixiv.net.", "type": 1, "TTL": 118, "data": "210.140.131.220"},{"name": "app-api.pixiv.net.", "type": 1, "TTL": 118, "data": "210.140.131.223"},{"name": "app-api.pixiv.net.", "type": 1, "TTL": 118, "data": "210.140.131.225"}]}
```

我想收集下哪些地方的网络被禁止连接

**Comment by Liupaperbox** [comment]
我的IP在山西，这里是全国的连通情况
![image](https://user-images.githubusercontent.com/46294886/73234533-81c8ba80-41c5-11ea-8282-1a49fdfdc3ff.png)
有部分地区无法访问，所以建议在代码中加多个DNS服务器，来应对不同地区的需求

**Comment by upbit** [comment]
这个图用什么工具绘制的？赞

从图里情况看，当失败时增加新的DNS解析是更合理的。方便的话，帮忙check下`dig.whois.com.au`这样的json接口是否可以访问（用于失败时补充调用），我再找找其他方便解析的json接口

**Comment by upbit** [comment]
curl给的几个DOH接口的地址，可以的话我这边也用这个工具，测试下哪几个DNS比较稳定：

https://github.com/curl/curl/wiki/DNS-over-HTTPS

**Comment by Liupaperbox** [comment]
我使用的是站长之家提供的[ping.chinaz.com](http://ping.chinaz.com/)，并且cloudflare-dns.com在山西可以访问。
能考虑一下代码对于 可用dns服务器 和 当前P站服务器ip 的缓存吗，这样说不定在下一次调用时会快一些

**Comment by upbit** [comment]
Good，估计域名是多个地址，我验证后尽快吧这个功能加上（后备地址）

pixivpy已经提供了类似接口，其实你看bypass api，只是解析出app-api的host，然后更新api.hosts。
如果你已经解析了地址，可以参考bapi.py最后的方式，通过[`set_api_proxy()`](https://github.com/upbit/pixivpy/blob/v3.5.4/pixivpy3/aapi.py#L22)来更新：

```py
api = ByPassSniApi()  # Same as AppPixivAPI, but bypass the GFW
api.require_appapi_hosts()
print(api.hosts)   # 保存并备用

# 使用之前的地址
api = AppPixivAPI()  # 或 api = ByPassSniApi()
api.set_api_proxy("https://210.140.131.220")
```

**Comment by upbit** [comment]
@Liupaperbox 可以用下面命令，更新下`v3.5.5-beta.1`分支下的pixivpy，试试bapi是否可以work了：

`pip install git+https://github.com/upbit/pixivpy.git@v3.5.5-beta.1 --upgrade`

如果发现pixivpy的版本没变化，可以先删除后重新安装下

**Comment by Liupaperbox** [comment]
抱歉，使用更新出现了错误
~~~
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    long_description=open('README.md', 'r').read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 300: illegal multibyte sequence
~~~
是setup.py里的错误
所以可以open('README.md', 'r', encoding='utf-8').read()

目前代码没有什么问题

**Comment by upbit** [comment]
ok。 utf-8的问题我修复后，merge到master下，到时你再试试

**Comment by upbit** [comment]
Fixed in 0829fa1a6452f20eb3499094b0a5385004d1696d

**Comment by upbit** [comment]
3.5.6已推送测试环境，包含了这个修改：

`pip install -i https://test.pypi.org/simple/ PixivPy --upgrade`

没问题的话，我再更新到正式环境

**Comment by Liupaperbox** [comment]
没有什么问题了，十分感谢！！

**Comment by upbit** [comment]
Upgraded to [v3.5.6](https://pypi.org/project/PixivPy/3.5.6/) to fix this issue
