### ISSUE TITLE
offset大于5000时返回error

### ISSUE THREAD

**Issue by liyijian316** [upbit/pixivpy#113]
使用aapi当offset大于5000时就会返回error：
`{'error': {'user_message': '', 'message': '{"offset":["Offset must be no more than 5000"]}', 'reason': '', 'user_message_details': {}}}`
既然**Offset must be no more than 5000**，那5000之后的怎么搜索呢？
试了好几个标签都是这样，但作品肯定不止5000件，pixiv网站上显示5w+
对于那些作品数量庞大的标签，有别的搜索办法吗?以及能否同时搜索多个标签呢？

**Comment by Rinacm** [comment]
> 使用aapi当offset大于5000时就会返回error：
> `{'error': {'user_message': '', 'message': '{"offset":["Offset must be no more than 5000"]}', 'reason': '', 'user_message_details': {}}}`
> 既然**Offset must be no more than 5000**，那5000之后的怎么搜索呢？
> 试了好几个标签都是这样，但作品肯定不止5000件，pixiv网站上显示5w+
> 对于那些作品数量庞大的标签，有别的搜索办法吗?以及能否同时搜索多个标签呢？

没办法，这就是限制，实际上webapi也有数量限制，public api的限制数量据我测试要略高于app api,可以尝试使用public api试试

**Comment by liyijian316** [comment]
那pubic和app的区别在哪？两个都是用的手机app接口吗？

**Comment by Xdynix** [comment]
> 那pubic和app的区别在哪？两个都是用的手机app接口吗？

PAPI的数量限制是约20000个作品，而AAPI的限制是5000。但是PAPI已经被废弃，虽然服务器还支持但是不知道什么时候会关闭。手机app目前用的是AAPI。

**Comment by liyijian316** [comment]
那没有网页版的吗( •̥́ ˍ •̀ू )网页版应该搜到的更多吧

**Comment by Xdynix** [comment]
网页版的确实有更多结果，但是会涉及recaptcha验证之类的问题，目前没什么库
