### ISSUE TITLE
Linux System ModuleNotFoundError: No module named 'pixivpy3'

### ISSUE THREAD

**Issue by akasakakona** [upbit/pixivpy#116]
My code worked just fine on Windows system but not Linux. Any solutions?

**Comment by Xdynix** [comment]
Maybe you can try to check if you have installed the package in the right environment. AFAIK, most Linux have Python 2 built-in, and `pip` will also install package for Python 2.

**Comment by akasakakona** [comment]
> Maybe you can try to check if you have installed the package in the right environment. AFAIK, most Linux have Python 2 built-in, and `pip` will also install package for Python 2.

Yes I checked it with `python3 -m pip show` because I have python 3.6 installed. It just won’t pick it up. I even tried rebooting the whole system.

**Comment by Xdynix** [comment]
That sounds strange. It works on my Linux (Centos 7, Python 3.6). The only way I can think about is to debug the import procedure. Like checking `sys.path` and verify whether the package is located in one of the directory.

**Comment by akasakakona** [comment]
> That sounds strange. It works on my Linux (Centos 7, Python 3.6). The only way I can think about is to debug the import procedure. Like checking `sys.path` and verify whether the package is located in one of the directory.

Got it, thanks for your help. Will try that out.
