### ISSUE TITLE
登录再次400

### ISSUE THREAD

**Issue by mwx2006** [upbit/pixivpy#117]
HTTP 400: Invalid header received from client.

**Comment by upbit** [comment]
可以提供更详细的信息吗？或者能复现的代码（注意把密码去掉下

**Comment by mwx2006** [comment]
from pixivpy3 import *
api=AppPixivAPI()
api.set_api_proxy("http://127.0.0.1:10809")
api.login(‘username','passwd')
print(api.illust_recommended(content_type="illust"))

**Comment by mwx2006** [comment]
Traceback (most recent call last):
  File "e:/Pix/main.py", line 4, in <module>
    api.login('username','passwd')
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\pixivpy3\api.py", line 81, in login
    return self.auth(username=username, password=password)
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\pixivpy3\api.py", line 120, in auth
    raise PixivError(
pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: Invalid header received from client.

**Comment by mwx2006** [comment]
版本的话是这个git库的

**Comment by upbit** [comment]
`http://127.0.0.1:10809`是你本地代理吗？如果要用本地代理访问，参考demo.py里的[例子](https://github.com/upbit/pixivpy/blob/master/demo.py#L25)

把`api.set_api_proxy("http://127.0.0.1:10809")`这行去掉，api_proxy不是代理，是`http://app-api.pixivlite.com`这样的专门代理服务

**Comment by mwx2006** [comment]
好的，我去试试

**Comment by mwx2006** [comment]
好了，谢谢
