### ISSUE TITLE
Recursively retrieving bookmark list

### ISSUE THREAD

**Issue by TianyiShi2001** [upbit/pixivpy#118]
目前貌似只能获取用户收藏第一页。不妨加入爬取完整的收藏列表的功能？

**Comment by Rinacm** [comment]
可以获取所有完整的收藏的啊(

**Comment by Rinacm** [comment]
你只需要自己填写参数就可以了

**Comment by TianyiShi2001** [comment]
> 你只需要自己填写参数就可以了

是`max_bookmark_id`吗

```python
def user_bookmarks_illust(self, user_id, restrict='public', filter='for_ios', max_bookmark_id=None, tag=None, req_auth=True):
```

**Comment by TianyiShi2001** [comment]
哦哦，原来是`favorite_works()`而不是`user_bookmarks_illust()`

**Comment by Rinacm** [comment]
> 哦哦，原来是`favorite_works()`而不是`user_bookmarks_illust()`

p站的很多appapi返回的json都带有一个next_url属性，代表的就是下一页的数据，一直递归的请求返回数据的next_url直到值为null为止就可以爬去完整的列表

**Comment by TianyiShi2001** [comment]
> > 哦哦，原来是`favorite_works()`而不是`user_bookmarks_illust()`
> 
> p站的很多appapi返回的json都带有一个next_url属性，代表的就是下一页的数据，一直递归的请求返回数据的next_url直到值为null为止就可以爬去完整的列表

嗯，我之前看`user_bookmarks_illust()`返回的结果时注意到了`next_url`, 但是直接`requests.get()`是不行的，所以感到困扰来提这个问题。

刚才研究了一下源码，现在发现了得用pixivpy里的`no_auth_requests_call()`和`parse_result()`。问题得到了解决。

**Comment by upbit** [comment]
不建议直接使用 no_auth_requests_call / parse_result，关于获取下一页数据，demo里有相关的演示：
https://github.com/upbit/pixivpy/blob/v3.5.6/demo.py#L56

```py
    json_result = aapi.illust_recommended(bookmark_illust_ids=[59580629])

    # get next page
    next_qs = aapi.parse_qs(json_result.next_url)
    json_result = aapi.illust_recommended(**next_qs)
```

**Comment by TianyiShi2001** [comment]
醍醐灌顶。谢谢！

**Comment by TianyiShi2001** [comment]
明白了，谢谢！
