### ISSUE TITLE
Login emails

### ISSUE THREAD

**Issue by luni3359** [upbit/pixivpy#119]
Is it normal to get so many pixiv login messages to email? How can I save the cookies so that pixivpy doesn't have to login every time a script runs?

**Comment by Xdynix** [comment]
Yes it's normal. You can save the string `api.refresh_token` to some file. And the next time you execute the script, use `api.auth(refresh_token=refresh_token)` instead of `api.login(username, password)` for authentication.

**Comment by luni3359** [comment]
Thank you very much, this is just what I needed. One more thing, do the refresh tokens expire?

**Comment by Xdynix** [comment]
Unfortunately there are no official documents about that. Because we are simulating the API request of the mobile client, and we do not need to log in frequently when using the mobile client, we can guess that it will not expire or have a long period, such as one month.

**Comment by luni3359** [comment]
Thank you.
