### ISSUE TITLE
关于api.py中的hash_secret字段

### ISSUE THREAD

**Issue by Helo-Man** [upbit/pixivpy#121]
我在学习你的源码的过程中发现授权过程中有使用到这个hash_secret与时间做一个凭接后再算一次hash的步骤。我想了解一下这个hash_secret字段是怎么的出来的，如果想要自己设置的话要怎么去获得？

**Comment by Mikubill** [comment]
当前用的hash_secret是解包Android APK得到的。ref: https://github.com/upbit/pixivpy/issues/92#issuecomment-546011823 https://github.com/upbit/pixivpy/issues/83#issuecomment-527163914 dup: https://github.com/upbit/pixivpy/issues/98

**Comment by Helo-Man** [comment]
哦哦好的谢谢，很明显我提出了一个很蠢的问题哈哈哈。
