### ISSUE TITLE
pixivpy can search novels?

### ISSUE THREAD

**Issue by wagawo** [upbit/pixivpy#127]
pixivpy can search novels?
I want to get the number of novel works

for illustrations I can use like this.
```
result = api.search_works('アリス・ギア・アイギス', mode='tag')
print(result.pagination.total)
```
resoponse like this
`{'status': 'success', 'response': [{'id': 81245036, ....}], 'count': 30, 'pagination': {'previous': None, 'next': 2, 'current': 1, 'per_page': 30, 'total': 5316, 'pages': 178}}`

I change like this
`api.search_works('アリス・ギア・アイギス', mode='tag', types=['novels'])`
but return 
`{'status': 'failure', 'has_error': True, 'errors': {'system': {'message': '400 Bad Request', 'code': None}}}`
Even if Ichange types=['novel']
Please tell me what I change.

Thanks for developing a nice library.
I'm sorry my poor english

**Comment by upbit** [comment]
PublicAPI's `search_work()` may not be able to search for novel. this API was released earlier, and search novels were not yet supported.

The new `AppAPI.search_illust` should be supported, but I don't pay attention to novel before, so pixivpy does not currently support `illust type` parameter:
https://github.com/upbit/pixivpy/wiki/Sniffer-for-iOS-6.x---Search-Tab

----------------

I will look at this problem later, after sniffing this search parameter, it will be added in the next version.

**Comment by wagawo** [comment]
Thank you for answering.
I'm looking forward to the update.

**Comment by upbit** [comment]
Added in [3.5.8](https://pypi.org/project/PixivPy/). First, upgrade PixivPy by `pip install pixivpy --upgrade`:

~~~py
    api = AppPixivAPI()
    api.login(_USERNAME, _PASSWORD)

    # search_target - 搜索类型
    #   partial_match_for_tags  - 标签部分一致
    #   exact_match_for_tags    - 标签完全一致
    #   text                    - 正文
    #   keyword                 - 关键词
    json_result = aapi.search_novel('FGO', search_target='keyword')
    print(json_result)
    novel = json_result.novels[0]
    print(">>> %s, origin url: %s" % (novel.title, novel.image_urls['large']))

    # get next page
    next_qs = aapi.parse_qs(json_result.next_url)
    json_result = aapi.search_novel(**next_qs)
    # print(json_result)
    novel = json_result.novels[0]
    print(">>> %s, origin url: %s" % (novel.title, novel.image_urls['large']))
~~~

**Comment by wagawo** [comment]
It Works!
Thank you!!
