### ISSUE TITLE
爬搜索页经常卡在那里很久

### ISSUE THREAD

**Issue by muyuqingqiu** [upbit/pixivpy#129]
代码里有没有超时重试的机制？

**Comment by upbit** [comment]
没有，这个实现的是客户端的原始接口，超时重试需要自己添加（比如初始化时设置requests的timeout）

另外可以看看异步API里是否有类似的重试机制
https://github.com/Mikubill/pixivpy-async

**Comment by muyuqingqiu** [comment]
好的 ，感谢。
