### ISSUE TITLE
Modify user bookmark-tag information

### ISSUE THREAD

**Issue by jjtapia** [upbit/pixivpy#130]
The App API method `user_bookmark_tags_illust` can currently be used to get user tags but not the images associated to each tag. Is it possible or are there plans to add this functionality to the project:

- Extract user bookmark tag information from an image (or conversely, extract the images associated to a user bookmark  tag)
- Add a custom user bookmark tag to a given image.

**Comment by upbit** [comment]
Are there similar functions on the Pixiv client `iOS or Android`? Can you make a screenshot?

The current ones are based on the client interface, which can be achieved if there is a similar write interface on the client.

**Comment by jjtapia** [comment]
There are two sections where user bookmarks/tags can be seen on the Android client. when browsing your personal collection, on the upper right part of the screen will appear a filter button

![image](https://user-images.githubusercontent.com/4514041/85188646-ed431f80-b26d-11ea-89a1-68d3c8d5face.png)


This allow you to filter your collection down to those images that have been previously tagged by the user.

Separately, when viewing an image if the user clicks on the like button

![image](https://user-images.githubusercontent.com/4514041/85188676-2085ae80-b26e-11ea-8edb-7c4fcd1b8f59.png)

An edit like window appears that allows the user to tag an image using a user defined bookmark/tag.

**Comment by upbit** [comment]
Got it.
I will look at this interface later

**Comment by jjtapia** [comment]
Using mitmproxy I intercepted the API calls. For filtering image it used the following url
```
 https://app-api.pixiv.net/v1/user/bookmarks/illust?user_id=<USERID>&restrict=public&tag=<USERTAGHERE>
```

**Comment by upbit** [comment]
En, `api.illust_bookmark_add` can add bookmark with tags, [see example](https://github.com/upbit/pixivpy/blob/0a951352d1eac7936c76b87217c49f20d42a603b/demo.py#L210):

```py
    illust_id = 74187223
    tags = ['Fate/GO', '50000users入り', '私服']
    json_result = api.illust_bookmark_add(illust_id, tags=tags)
```

You can [get user tags](https://github.com/upbit/pixivpy/blob/0a951352d1eac7936c76b87217c49f20d42a603b/pixivpy3/aapi.py#L356) by `api.user_bookmark_tags_illust()`, then `api.user_bookmarks_illust(userid=api.user_id, tag='sometag')`
