### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by emesh0620** [upbit/pixivpy#141]
> cloudscraper.exceptions.CloudflareCaptchaProvider: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.

When I was using it in a production environment, I got an error like the one above and I can't log in to Pixiv.
Strangely, it works fine in the test environment. Did you block the IP address?

**Comment by upbit** [comment]
This looks like #140 add cloudscraper involved. Which version is your cloudscraper? `>1.2.30`?

**Comment by upbit** [comment]
Due to #140 case, we use cloudscraper bypass auth check. But cloudscraper cannot skip Captcha, if your IP is blocked by Cloudflare, you will not be able to bypass access to the /auth interface.

Request failed: Cloudflare reCaptcha detected
https://github.com/SickChill/SickChill/issues/5952

**Comment by emesh0620** [comment]
With version 1.2. 48 of cloudscraper, PixivPy is, of course, the latest.

**Comment by upbit** [comment]
> With version 1.2. 48 of cloudscraper, PixivPy is, of course, the latest.

First, change another IP to access Cloudflare (Pixiv).
Second, try revert to 3.5.9, which not use cloudscraper (which direct request, high probability will return 403)

If none of the above methods work, try the [example_bypass_sni.py](https://github.com/upbit/pixivpy/blob/master/example_bypass_sni.py#L23) method to directly access the Pixiv server

**Comment by emesh0620** [comment]
Thank you. However, it seems that the server you are using cannot change the IP address, so I'm in trouble. For example, can't I use a proxy? Incidentally, in a test environment, the exact same source code works fine.

**Comment by emesh0620** [comment]
Go back to 3.5. 9 and you'll see the HTML source code saying "CAPTCHA certification.". I will try the third one for now.

**Comment by emesh0620** [comment]
Thank you. The IP address is hard to change in a production environment, so I tried it in a test environment, and it worked with the source code which is completely the same as the production.

Also, back to PixivPy's 3.5. 9, you'll see the HTML source code that says "CAPTCHA certification.".

My guess is that the IP address is blocked. Can't I access Pixiv API via proxy? I will try the third one for now.

**Comment by emesh0620** [comment]
After that, an error suddenly occurred without changing SQLite 3 or the source code, so I created a whole instance of the production VPS and fixed it.

The IP address has also changed, so I don't know which is the cause, but it has been solved.
Thank you for your consultation.

**Comment by upbit** [comment]
> Thank you. The IP address is hard to change in a production environment, so I tried it in a test environment, and it worked with the source code which is completely the same as the production.
> 
> Also, back to PixivPy's 3.5. 9, you'll see the HTML source code that says "CAPTCHA certification.".
> 
> My guess is that the IP address is blocked. Can't I access Pixiv API via proxy? I will try the third one for now.

Yes, your IP address may blocked by Cloudflare. Create a new VPS will change IP (usually), the example_bypass_sni.py method should also work as well (I guess)

**Comment by HateNoSaiShi** [comment]
You could check your openssl version because the required version to support TLS is 1.1.1.
