### ISSUE TITLE
OpenSSL  does not meet the minimum supported version

### ISSUE THREAD

**Issue by animemoeus** [upbit/pixivpy#143]
It's works in my local, but not work in the production server.

```python
>>> from pixivpy3 import AppPixivAPI
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
>>> api = AppPixivAPI()
>>> api.login('john.doe@mail.com','password')
cloudscraper.exceptions.CloudflareCaptchaProvider: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.

During handling of the above exception, another exception occurred:

pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
>>> 
```

**Comment by chitosai** [comment]
I'm encountering the same problem, keeps getting Cloudflare Captcha error.

I'm runing python2.7 on ubuntu 16.04. I tried to compile a new version for ubuntu.
`openssl version
OpenSSL 1.1.1h  22 Sep 2020`

However my python still recognize the old version:
`Python 2.7.12 (default, Jun  9 2018, 23:36:54) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2g  1 Mar 2016'`

How can I fix it? Thanks!

**Comment by Xdynix** [comment]
Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.

**Comment by chitosai** [comment]
> Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.

Hi, do you mean python3 has openssl 1.1.1 built-in and can meet the requirement?
If it does, I'll surly switch to python3.

**Comment by Xdynix** [comment]
> > Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.
> 
> Hi, do you mean python3 has openssl 1.1.1 built-in and can meet the requirement?
> If it does, I'll surly switch to python3.

I have checked with Python 3.7.9 on Windows 7 and Python 3.8.6 on Windows 10. Both have OpenSSL 1.1.1 built-in.

**Comment by chitosai** [comment]
> > > Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.
> > 
> > 
> > Hi, do you mean python3 has openssl 1.1.1 built-in and can meet the requirement?
> > If it does, I'll surly switch to python3.
> 
> I have checked with Python 3.7.9 on Windows 7 and Python 3.8.6 on Windows 10. Both have OpenSSL 1.1.1 built-in.

Okay I'll try upgrade it, hope that works.
Thanks very much!

**Comment by animemoeus** [comment]
> Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.

I'm using python 3.7, the same environment as my local.
Looks like the problem is in my hosting provider.

I just confuse why the same environment not work.

```python
(env:3.7)[user@host]$ python
Python 3.7.8 (default, Aug 11 2020, 06:58:33) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pixivpy3 import AppPixivAPI
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
>>> api = AppPixivAPI()
>>> api.login('john.doe@mail.com','password')
cloudscraper.exceptions.CloudflareCaptchaProvider: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.

During handling of the above exception, another exception occurred:

pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
>>> 

```

**Comment by Xdynix** [comment]
> > Why not just migrate to Python 3? Even Python officially stopped supporting Python 2 at the beginning of this year. You cannot expect third-party developers to continue to provide compatibility with them.
> 
> I'm using python 3.7 in production, the same environment as my local.
> Looks like the problem is in my hosting provider.
> 
> I just confuse why the same environment not work..
> 
> ```python
> (env:3.7)[user@host]$ python
> Python 3.7.8 (default, Aug 11 2020, 06:58:33) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from pixivpy3 import AppPixivAPI
> DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
> >>> api = AppPixivAPI()
> >>> api.login('john.doe@mail.com','password')
> cloudscraper.exceptions.CloudflareCaptchaProvider: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
> 
> During handling of the above exception, another exception occurred:
> 
> pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
> >>> 
> ```

Hmmm... It seems that Python does not have built-in OpenSSL on Linux, but instead uses the one on the system. I am not familiar with the development of Linux environment, so I can only recommend upgrading OpenSSL and reinstalling Python.

**Comment by upbit** [comment]
> I'm encountering the same problem, keeps getting Cloudflare Captcha error.
> 
> I'm runing python2.7 on ubuntu 16.04. I've compiled openssl 1.1.1h manually.
> `openssl version`
> `OpenSSL 1.1.1h 22 Sep 2020`
> 
> However my python still recognize the old version:
> `Python 2.7.12 (default, Jun 9 2018, 23:36:54) `
> `[GCC 5.4.0 20160609] on linux2`
> `Type "help", "copyright", "credits" or "license" for more information.`
> `>>> import ssl`
> `>>> ssl.OPENSSL_VERSION`
> `'OpenSSL 1.0.2g 1 Mar 2016'`
> 
> How can I fix it? Thanks!

It seems that although OpenSSL 1.1.1 is compiled, your python is still an old version. You can try to install the 1.1.1 development package, and then specify the include path when compiling Python2.

However, there are many dependency problems in compiling python. It is recommended to find out if anyone else has packaged Py2 for your OS.

**Comment by upbit** [comment]
> ```python
> Captcha detected
> ```

In addition, if it says "Captcha detected", the IP may be blocked.
I don't know much about [cloudscraper.create_scraper()](https://github.com/upbit/pixivpy/blob/v3.5.10/pixivpy3/api.py#L31), so I don't add any additional parameters currently. According to the error message, see if there is a solution for the cloudscraper example: https://github.com/VeNoMouS/cloudscraper

**Comment by animemoeus** [comment]
> > ```python
> > Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
> > ```
> 
> @animemoeus In addition, if it says "Captcha detected", the IP may be blocked, try change another IP if you can.
> 
> I don't know much about [cloudscraper.create_scraper()](https://github.com/upbit/pixivpy/blob/v3.5.10/pixivpy3/api.py#L31), so I don't add any additional parameters currently. According to the error message, see if there is a solution for the cloudscraper example: https://github.com/VeNoMouS/cloudscraper

I can't change the IP from the server, but when I try to use ubuntu server 18 there is no problem.

So I confident the problem is from my hosting providers that use Centos/Red Hat

**Comment by upbit** [comment]
> 
> I can't change the IP from the server, but when I try to use ubuntu server 18 there is no problem.
> 
> So I confident the problem is from my hosting providers that use Centos/Red Hat

Emmm, it sounds like what @Xdynix said: related to old OpenSSL

**Comment by animemoeus** [comment]
> > I can't change the IP from the server, but when I try to use ubuntu server 18 there is no problem.
> > So I confident the problem is from my hosting providers that use Centos/Red Hat
> 
> Emmm, it sounds like what @Xdynix said: related to old OpenSSL, upgrade will fix this

Yeah, I think an upgrade will fix the problem

Sadly, I'm don't have root access to hosting.

**Comment by chitosai** [comment]
Spent some time to fix it today.

Experience for ubuntu users:  migrate code to python3, upgrade ubuntu to at least 18.04, then make sure to install openssl from `bionic-updates` source. That will upgrade ssl module of python3 to 1.1.1.
