### ISSUE TITLE
Public API me_favorite_works_add() and other api calls do not work

### ISSUE THREAD

**Issue by Yochyo** [upbit/pixivpy#145]
Error message: `{'system': {'message': '404 Not Found', 'code': None}}`

me_favorite_works() and me_feeds() also don't seem to be working and return the same error.

Is the public api deprecated?

**Comment by upbit** [comment]
Emm.. It looks like it has been killed.
Public-API is the earliest version, the client is no longer used a few years ago, you can try to switch to App-API

**Comment by Yochyo** [comment]
Thank you a lot.
