### ISSUE TITLE
auth() failed invalid_grant error

### ISSUE THREAD

**Issue by asdMild** [upbit/pixivpy#147]
[ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}},"error":"invalid_grant"}

**Comment by Xdynix** [comment]
`103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。`

Indicates that your email address and password do not match.

**Comment by nassie256** [comment]
When the password was too simple (short), I got this error even if the ID / password was correct.
I solved it by changing the 9 character password to 14 characters.

**Comment by smartphone-pro** [comment]
I faced the same error.
The password has been changed to 16 characters.
But there is still the same error.
Until a few days ago, it was working.
Please help me.

**Comment by upbit** [comment]
First of all, `103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください`
this error is still related to the password, if it is not affected by the length, try changing a complex password (uppercase and lowercase letters, numbers).

You can also pay attention to whether there are other prompts in the error.

**Comment by smartphone-pro** [comment]
I changed the password.
Even I tried with other account.
But the results are same.

`{
  "error" : "invalid_grant",
  "has_error" : true,
  "errors" : {
    "system" : {
      "message" : "103:pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。",
      "code" : 1508
    }
  }
}`

**Comment by JudasV** [comment]
pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"The grant type is unauthorized for this client_id","code":1508}},"error":"invalid_grant"}
The same code, no problem on my company’s computer, but this error on my personal computer
