### ISSUE TITLE
ByPassSniApi.illust_ranking function parameter "offset" dont work

### ISSUE THREAD

**Issue by zangxx66** [upbit/pixivpy#153]
I only need a few results, and setting offset won't work

**Comment by Xdynix** [comment]
`offset` is used for pagination. There are currently no parameters to control the number of results returned.

**Comment by upbit** [comment]
像 @Xdynix 解释的，offset其实是客户端用于翻页的，AppAPI目前没有发现`size`这样的参数，来控制返回条数

两个方案：
1. 自己分页（比如每次返回一半），下次还是保持offset，返回另一半；
1. 可以利用offset，自己记录并覆盖这个值：比如接口每页返回20条，对外返回10条，那么下次把offset=20改成offset=10；（不太推荐，不确定这样会不会导致Pixiv的cache失效；如果你的请求频率很高，可能会被ban）
