### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER报错

### ISSUE THREAD

**Issue by anananan116** [upbit/pixivpy#154]
使用AppPixivAPI login()时报错
pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: HTTPSConnectionPool(host='oauth.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
切换到bypass方法后报错：
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cloudflare-dns.com', port=443): Max retries exceeded with url: /dns-query?ct=application%2Fdns-json&name=public-api.secure.pixiv.net&type=A&do=false&cd=false (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024C40CB3D00>, 'Connection to cloudflare-dns.com timed out. (connect timeout=3)'))
前一段时间使用正常方法也可以登陆，近三四天无法登陆
网络使用v2ray全局代理
望解决，十分感谢！

**Comment by upbit** [comment]
试了下ByPass的方法，没有遇到类似的情况（倒是提示`103:pixiv ID`密码错误，登录改密码后正常）
```json
HTTP 400: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}},"error":"invalid_grant"}
```

从你的错误提示看，推测可能是SSL证书的问题（还没到auth这步），可以尝试换个python环境或镜像试试。

**Comment by AlphaBoom** [comment]
相同的问题，v2ray开了全局代理后有这个报错
