### ISSUE TITLE
The ugoira_metadata feature cannot get the URL of the original source.

### ISSUE THREAD

**Issue by shibababa** [upbit/pixivpy#164]
Currently, the only'zip_urls' that can be obtained by api.ugoira_metadata (illust_id) is'medium', not the original source URL.

For example, you can get ugoira600x600.zip but not ugoira1920x1080.zip.

Please correct it if possible.

**Comment by upbit** [comment]
The fields of ugoira are determined by Pixiv, and the API does not modify the contents.
If the zip_urls contains a low-resolution zip, you may have to extract the higher-resolution zip yourself (from other fields)
