### ISSUE TITLE
POST: Auth, connection aborted

### ISSUE THREAD

**Issue by Aaeeschylus** [upbit/pixivpy#165]
Been using this for a few months now, however as of today, it is no longer working. 

I tried generating a new refresh token, just incase that was the problem, however I am now getting the following error:

`PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: ('Connection aborted.', OSError(0, 'Error'))`

Have Pixiv changed how the auth flow works again?

**Comment by upbit** [comment]
Can you provide more detailed information?
`Connection aborted.` It is mean that the proxy is unavailable, or the domain name is resolved to CloudFlare

**Comment by Aaeeschylus** [comment]
Im not too sure how much more details I can give than the following:

```
pixivapi = pixivpy3.AppPixivAPI()
PIXIV_REFRESH = os.getenv('PIXIV_REFRESH')
pixivapi.auth(refresh_token=PIXIV_REFRESH)
```

It hangs for a little bit and then throws the error on the auth function.

**Comment by Xdynix** [comment]
The certification workflow should not have changed, it is normal on my side. I tend to guess that this is a network problem when connecting to Pixiv. Can you try to access Pixiv directly on the web browser? I have encountered some situations where Pixiv forbids some IDC IPs from accessing them, or the machine clock error is too large and the SSL verification fails, etc., but I am not sure whether these apply to your situation. In the worst case, I think using a proxy server should solve this problem.

**Comment by Aaeeschylus** [comment]
> The certification workflow should not have changed, it is normal on my side. I tend to guess that this is a network problem when connecting to Pixiv. Can you try to access Pixiv directly on the web browser? I have encountered some situations where Pixiv forbids some IDC IPs from accessing them, or the machine clock error is too large and the SSL verification fails, etc., but I am not sure whether these apply to your situation. In the worst case, I think using a proxy server should solve this problem.

I logged into pixiv through the browser on the computer that I have the script running from and it worked perfectly fine. I checked the machine clock just incase and there is no error there.

**Comment by Aaeeschylus** [comment]
I downgraded from 3.5.11 to 3.5.10 and everything is working fine again.

**Comment by upbit** [comment]
`3.5.11` There is no change to the `auth`. If you can solve it only by downgrading, there is a high probability that the network connection is restored.
You can try to upgrade again (only upgrade the version of `PixivPy`), it should also work.

**Comment by Aaeeschylus** [comment]
I upgraded again and it seems to be working again for now. I am still quite confused because right before I downgraded I tested one more time and it still didn't work, but immediately started working again after the downgrade.
