### ISSUE TITLE
POST:Detected a Cloudflare version 2 Captcha challenge

### ISSUE THREAD

**Issue by bakashigure** [upbit/pixivpy#166]
after using refresh_token for a few months, the problem appeared today,
i have tried to regenerate a new fresh_token, but it`s the same as the old one...

    Traceback (most recent call last):
    cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.`

**Comment by bakashigure** [comment]
this problem doesn`t appear every time, only once in about four to five requests

**Comment by upbit** [comment]
This problem is thrown by cloudscraper. If there is a need to bypass, you can refer to its documentation to configure a paid bypass proxy.

At present, it mainly relies on cloudscraper to resolve the correct host. The simpler way of processing is to change the proxy or refresh repeatedly.

**Comment by bakashigure** [comment]
I get it, thanks. 

The solution I'm using now is to repeat the request, which doesn't completely solve the problem, but at least it's better.
