### ISSUE TITLE
download() still works when status code is 404

### ISSUE THREAD

**Issue by Antares0982** [upbit/pixivpy#167]
I tried to download all illustrations from an url (the url is from other source). My code is:

```python3
i = 0
while True:
    try:
        api.download(
            url+str(i)+'.jpg', path=path, name=None)
        i += 1
    except:
        break
```

But it didn't break as I expected. So I modified the method download() and it works fine:
```python3
def download(pixivapi:AppPixivAPI, url, prefix='', path=os.path.curdir, name=None, replace=False, fname=None,
                referer='https://app-api.pixiv.net/'):
    """Download image to file (use 6.0 app-api)"""
    if fname is None and name is None:
        name = os.path.basename(url)
    elif isinstance(fname, basestring):
        name = fname

    if name:
        name = prefix + name
        img_path = os.path.join(path, name)

        if os.path.exists(img_path) and not replace:
            return False

    response = pixivapi.requests_call('GET', url, headers={'Referer': referer}, stream=True)
    print(response.status_code)
    ### Only added two lines
    if response.status_code == 404:
        raise PixivError("404 Not Found")
    ###
    if name:
        with open(img_path, 'wb') as out_file:
            shutil.copyfileobj(response.raw, out_file)
    else:
        shutil.copyfileobj(response.raw, fname)
    del response
    return True

while True:
    try:
        download(pixivapi,
            url+str(i)+'.jpg', path=path, name=None)
        i += 1
    except PixivError:
        break
```

So my problems are:
* Do you mind raise an exception if the status code is not proper when using download()?
* Can I get the number of illustrations from an url starting with `https://i.pximg.net` or `https://www.pixiv.net` directly, using pixivpy? If can, downloading illustrations would be easier for me.
* Will pixivpy support typing?

**Comment by Xdynix** [comment]
1. In that case you can just simply use `requests` directly do fetch the URL. All you need is to add header `Referer: https://app-api.pixiv.net/`. E.g.:

   ```python
   with requests.get(url, headers={'Referer': "https://app-api.pixiv.net/"}, stream=True) as response:
       response.raise_for_status()
       with open('output-file.jpg', 'wb') as file:
           for chunk in response.iter_content(chunk_size=8192):
               file.write(chunk)
   ```

2. Sure. This is what `pixivpy` intended for.

   ```python
   from pixivpy3 import AppPixivAPI


   def main():
       api = AppPixivAPI()
       api.auth(refresh_token=refresh_token)

       # Multi-pages
       response = api.illust_detail('88588799')
       for page in response.illust.meta_pages:
           url = page.image_urls.original
           print(url)

       # Ugoria (Animated Illust)
       response = api.ugoira_metadata('89218824')
       url = response.ugoira_metadata.zip_urls.medium
       frames = response.ugoira_metadata.frames
       print(url)
       print(frames)


   if __name__ == '__main__':
       main()
   ```

   However, you'll have to login to fetch these metadata. And it's a little complicated to retrieve the refresh token. Refer to #158 for possible approaches.

   Also check the README.md and example.py for other usage.

3. I'm not the author of this package. Just a little bit of my own opinion. The schema of the JSON returned by the API is determined by the Pixiv server, so it may change. And the content of the response is not complicated, so the type annotation may not be very helpful. And it will also break the compatibility of the package. Although the officially supported version of Python has reached 3.6, I still see users in the community who use Python 2.

**Comment by Antares0982** [comment]
Thank you, that's very helpful! :)
