### ISSUE TITLE
帅哥Past-R18 Daily这个接口你怎么找到的，我抓来抓去也没找到这个接口...

### ISSUE THREAD

**Issue by zzycami** [upbit/pixivpy#17]
帅哥Past-R18 Daily这个接口你怎么找到的，我抓来抓去也没找到这个接口...虚心求教

**Comment by upbit** [comment]
R18类需要在帐号设置里打开r18开关，然后从排行榜的【过去排行】里找（因此Past类榜单必须传`date=2016-07-08`参数）

**Comment by zzycami** [comment]
多谢，不知道怎么过IOS审核的，哈哈哈，只能说官方真牛逼

**Comment by upbit** [comment]
Pixiv的iOS评级是17+的，所以少量未打R18标签的擦边图可以过审。
另外想绕过审核，一般是对未登录用户或默认关掉R18榜单的选项。估计apple审核员也不会特意去web打开这个，哈哈。

**Comment by zzycami** [comment]
我下次也试试，直接更具账号是否开启了R18选项， 不过我还是觉得以前的老接口可以获取当天的R18排名更加方便，最近在对应用进行新的接口的跟新，真是折腾。

**Comment by upbit** [comment]
更猥琐的办法是对还在审核的版本号做版本号判断，拉配置时隐藏掉一些新特性，哈哈。

嗯，是啊。老接口挺不错的，比如[Public-API的搜索接口](https://github.com/upbit/pixivpy/wiki/Sniffer-for-iOS-6.x---Search-Tab#%E6%90%9C%E7%B4%A2%E6%97%A7%E7%89%88)还能拉取1页热门排行。
新的iOS App目前更新太频繁，所以不是新功能可以考虑不更新`app-api`（Public-API应该不会停，毕竟iOS8以下的客户端还要用的）

**Comment by zzycami** [comment]
恩，这个办法我也想过，也是可以的，毕竟绕过审核还不是什么难事，我这边部分功能换新接口，为了兼容老接口需要做挺大调整的，因为字段都不一样了（这要是这个比较坑）。顺便提下mac上用青花瓷抓包挺好的，之前一直找不到好用的就只能用你提供的现成接口了，多谢了。

**Comment by upbit** [comment]
哈哈，是的，还有那个next_url参数，开始还以为掉错成Web API了。
接口我现在抓的不全，而且缺乏参数和返回字段的具体文档，这块也确实挺头疼的，互相交流 :)

**Comment by zzycami** [comment]
分页现在直接把offset这个参数放到了next_url这个字段里面了，我这边使用swift写的，有需要可以给你提供一份参考，新的接口我直接通过next_url获取下一页内容，需要字段的话直接解析next_url。没办法，不过现在接口确实比以前整洁了，端口返回结果同意，命名清晰，确实越来越好。毕竟我是很喜欢P站的，想要自己搞点自己喜欢的功能。现在不需要登录也可以获取很多接口的数据了，我看你那边没写这些。毕竟看看普通的每日排行榜还需要登录确实不好

**Comment by upbit** [comment]
好的，不用登录的接口，我回头去你的repo里参考下
另外，next_url里还会带特殊参数，例如[推荐接口](https://github.com/upbit/pixivpy/blob/5140589f5feda6811656a1871aa0a263707bac9d/pixivpy3/api.py#L500)的 `max_bookmark_id_for_recommend / min_bookmark_id_for_recent_illust` 参数

**Comment by zzycami** [comment]
我没跟新在原来的那个工程里，换工程了，现在新版重构还没完成，等我文档完善，我会把工程po出来，完成了就会通知你的，也算是提供了swift版本的接口可供使用，文档会给出你python版本的地址的。

**Comment by zzycami** [comment]
![qq20160725-0 2x](https://cloud.githubusercontent.com/assets/1886034/17093352/53bf3caa-527b-11e6-866c-8f24e7164d55.png)
其实特简单，就是不带认证参数而已，然后我抓取了注册功能的相关接口，认证在没有获取token的时候会设置Bearer WHDWCGnwWA2C8PRfQSdXJxjXp0G6ULRaRkkd6t5B6h8这个字符，默认的，我测试过不会动

**Comment by zzycami** [comment]
我把我的QQ给你吧，576452467，方便互相做交流。Web，Android，IOS，前端我都会，这方便的技术交流也可以的！

**Comment by upbit** [comment]
收到:)
