### ISSUE TITLE
[Request] API possible to return "phpsessid"?

### ISSUE THREAD

**Issue by cykac04** [upbit/pixivpy#170]
I need the phpsessid value for parsing notification of pixiv sketch.
Only web response has the m3u8 url.
App response also has a list but there is no m3u8 url.

**Comment by Xdynix** [comment]
The `phpsessid` is only available on website. The App is using OAuth (`access_token` and `refresh_token`), and `pixivpy` is using the App API. So it has no way to do with `phpsessid`. You should consider pretending to be a browser to send login requests (maybe use Selenium to fill the form and click login button), and then fetch the cookie.

**Comment by upbit** [comment]
Consider simulating the login on the WEB side, and [obtain PHPSESSID through cookiejar](https://github.com/upbit/pixivpy/issues/155#issuecomment-769518074). If you are not using the WEB login method, it is impossible to obtain the normal PHPSESSID
