### ISSUE TITLE
Rate Limit 大概要怎么去避免撞上呢

### ISSUE THREAD

**Issue by djkcyl** [upbit/pixivpy#173]
要高频访问 illust_detail 基本一两分钟内就会报 Rate Limit，想知道一个具体的值

**Comment by Xdynix** [comment]
Pixiv没有公开API使用，我们用这些lib都是偷偷摸摸的，怎么可能有个具体的值呢。就算试出来了，Pixiv以后也可能随时调整，不如保险点，每次访问后等随机的几秒，也别给他们服务器增加太多压力。

**Comment by djkcyl** [comment]
> Pixiv没有公开API使用，我们用这些lib都是偷偷摸摸的，怎么可能有个具体的值呢。就算试出来了，Pixiv以后也可能随时调整，不如保险点，每次访问后等随机的几秒，也别给他们服务器增加太多压力。

嗯，我现在大概就是请求一次就sleep一下，要是撞上了就sleep10分钟

**Comment by assassingyk** [comment]
感觉Rate Limit似乎和ip有关？我是每次请求随机等了一秒左右，同一家梯子有的节点几分钟就rate limit，有的就一小时都没事……
