### ISSUE TITLE
有没有办法通过作品ID获取到作品的原图地址？

### ISSUE THREAD

**Issue by Steven52065** [upbit/pixivpy#178]
id=pixiv作品的ID
api = pixivpy3.AppPixivAPI(**_REQUESTS_KWARGS)
api.auth(refresh_token=_REFRESH_TOKEN)
illust_result = api.illust_detail(illust_id=id)['illust']
pic_url = illust_result['image_urls']['large']
r = requests.get(pic_url, headers={'Referer': 'https://www.pixiv.net/',"User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9.1.6) "},proxies=proxies)

这是我的代码，但这个url好像也并不是原图吧，求大佬指点迷津，感谢

**Comment by upbit** [comment]
参考download的例子，取 `original_image_url`：
https://github.com/upbit/pixivpy/blob/master/download_illusts.py#L40

**Comment by Steven52065** [comment]
> 参考下载的例子，取`original_image_url`：
> https://github.com/upbit/pixivpy/blob/master/download_illusts.py#L40

感谢大佬的帮助
