### ISSUE TITLE
如何使用我自己的http代理或者socks5代理

### ISSUE THREAD

**Issue by djkcyl** [upbit/pixivpy#180]
如题

**Comment by Xdynix** [comment]
`AppPixivAPI()`的关键字参数会直接被传入`requests`。
```
from pixivpy3 import AppPixivAPI


proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
api = AppPixivAPI(proxies=proxies)
```

Ref: <https://docs.python-requests.org/en/master/user/advanced/#proxies>

如果要使用socks5代理，则需要为`requests`安装额外的依赖：<https://docs.python-requests.org/en/master/user/advanced/#socks>

**Comment by djkcyl** [comment]
明白了，谢谢
