### ISSUE TITLE
获取受男性欢迎的日榜第一名缺失的问题

### ISSUE THREAD

**Issue by yuejieyao** [upbit/pixivpy#183]
我尝试使用illust_ranking获取mode='day_male'的榜单,发现和实际网页上相比会缺失第一名,而mode='day'就是正常的
请问这个是P站API的问题吗?不知道是我个例还是都这样?
下面是我的代码
```
import os
from pixivpy3 import *
import datetime

app = AppPixivAPI()
directory = "illusts"
if not os.path.exists(directory):
    os.makedirs(directory)

app.auth(refresh_token='xxxxxxxxxxxxxxxxx')
t = (datetime.datetime.today()-datetime.timedelta(days=2)).date()
json_result = app.illust_ranking(mode='day_male', date=t)
print(json_result.illusts)
```

**Comment by upbit** [comment]
这个还真没留意过，API并不会对返回的内容做处理，所以一般少了数据，可能是P站的特殊逻辑。
可以看看少的那个结果，是不是有特殊的地方（比如右上有广告角标，或者是热门作品的top1插入的）

如果有结论，欢迎反馈

**Comment by Xdynix** [comment]
在我这里看着是正常的：
![代码及结果](https://user-images.githubusercontent.com/14145832/132787494-bf8e8c64-964f-4682-850c-2336f4b3b5cf.png)
![网页](https://user-images.githubusercontent.com/14145832/132787498-07c6a0ec-dbd6-4a2b-82ca-4e9b4a90c0b6.png)

**Comment by yuejieyao** [comment]
> 在我这里看着是正常的：

我这里获取9月7号拿到的第一个就是你图里的第二名,挺奇怪的
![image](https://user-images.githubusercontent.com/6092095/132788492-87db83f7-21f1-4993-9cf0-cf376040dea1.png)

**Comment by Xdynix** [comment]
排名第一的图92578505，有`'sanity_level': 6`这个属性。后续的图基本上只有`'sanity_level': 2`。是否有可能是账户设置里因为没有打开浏览限制被隐藏了？

**Comment by yuejieyao** [comment]
> 排名第一的图92578505，有`'sanity_level': 6`这个属性。后续的图基本上只有`'sanity_level': 2`。是否有可能是账户设置里因为没有打开浏览限制被隐藏了？

我使用隐私模式在没有登录的情况下打开网页也是能显示第一名的图片的,按理不应该有限制吧,不过我还是决定去尝试一下

**Comment by upbit** [comment]
你看看账户的 R-18 标记。这个要网页设置才能展示的，如果不设P站服务端就会过滤掉

**Comment by yuejieyao** [comment]
还真是R18标记,那个图虽然不用登录也能看,并且也并不是R18的图,但是不在设定里打开R18,API就获取不到,真的够迷的
感谢大家的帮助!
