### ISSUE TITLE
PixivAPI() 的部分功能好像失效了

### ISSUE THREAD

**Issue by lancer-wang** [upbit/pixivpy#185]
api.ranking()
返回的结果是下面这个
{'status': 'failure', 'has_error': True, 'errors': {'system': {'message': '404 Not Found', 'code': None}}}

使用AppPixivAPI() 可以正常获取数据

**Comment by upbit** [comment]
PAPI是几年前的老版本了，不少接口都已经失效。建议是换到新版本的 AppAPI
