### ISSUE TITLE
Papi no longer works

### ISSUE THREAD

**Issue by ImoutoChan** [upbit/pixivpy#186]
So we only have AppApi now. Does it mean there is no longer a way to get R18 rankings? As far as I see there are only safe modes.

**Comment by Xdynix** [comment]
```python
from pprint import pprint

from pixivpy3 import AppPixivAPI


def main():
    api = AppPixivAPI()
    api.auth(refresh_token='xxx')
    json_result = api.illust_ranking(mode='week_r18')
    pprint(json_result)


if __name__ == '__main__':
    main()
```

The R18 ranking is working well on AppPixivAPI. Have you turned off the R18 filtering setting in your account?

![Snipaste_2021-09-23_15-37-09](https://user-images.githubusercontent.com/14145832/134593063-a750b904-30cd-4896-9b54-60ea1f2bbee0.png)

**Comment by ImoutoChan** [comment]
Thank you! The settings were the problem. I was confused by this `(Past)` comment.
```
# mode (Past): [day, week, month, day_male, day_female, week_original, week_rookie,
#               day_r18, day_male_r18, day_female_r18, week_r18, week_r18g]
```
