### ISSUE TITLE
latest_works

### ISSUE THREAD

**Issue by potpotkettle** [upbit/pixivpy#189]
I used latest_works of the old API in the past. It does seem to work any more. https://public-api.secure..net/v1/works.json returns {"status":"failure","has_error":true,"errors":{"system":{"message":"404 Not Found","code":null}}}

Is there anything I can use instead? Any workaround?

**Comment by upbit** [comment]
`latest_works` API has not yet provided an interface, I will send you a try after verification:

* Everyone's new work
Illustration: https://app-api.pixiv.net/v1/illust/new?content_type=illust&filter=for_ios
* Comic: https://app-api.pixiv.net/v1/illust/new?content_type=manga&filter=for_ios

**Comment by upbit** [comment]
Upgrage to v3.6.1, and use `api.illust_new()` instead
https://pypi.org/project/PixivPy/3.6.1/

**Comment by potpotkettle** [comment]
@upbit: https://github.com/upbit/pixivpy/commit/024d4e7212582ca6f31ef5592b4b5b46cb351cbc#commitcomment-60727126
