### ISSUE TITLE
Any API to get illust details?

### ISSUE THREAD

**Issue by Nandaka** [upbit/pixivpy#19]
Just want to ask if there is any API to get the illustrations details (e.g. title, caption, urls) for given illust_id without go through the user_id illustrations?

**Comment by MrBloodyshadow** [comment]
https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L141

**Comment by upbit** [comment]
Yes, **Public-API** has `PixivAPI().works(illust_id)` to get illust details

**NOTICE**: AppAPI() has no api.works() interface, the 6.x API always return a list of works.

**Comment by Nandaka** [comment]
any idea to get the ```ugoira1920x1080``` url using public api?
e.g illust_id = 59422835

![image](https://cloud.githubusercontent.com/assets/836867/19357909/33b1885e-91a6-11e6-80b9-9acf1182c83e.png)

**Comment by MrBloodyshadow** [comment]
If you only want to download that one you can use some web that downloads it as webm or gif like [this one](http://ugoira.dataprocessingclub.org/). I don't know if that can be done with the pixivpy I havent tried ugoiras yet.

**Comment by upbit** [comment]
~~~py
from pixivpy3 import *

def main():
    api = PixivAPI()
    api.login(_USERNAME, _PASSWORD)

    json_result = api.works(59422835)
    illust = json_result.response[0]
    print("origin url: %s" % illust.image_urls.large)
~~~

`illust.image_urls.large` is the origin url for illusts: `http://i4.pixiv.net/img-original/img/2016/10/11/14/52/13/59422835_ugoira0.jpg`

**Comment by Nandaka** [comment]
@upbit

not really, that is more like a preview image for the actual ugoira (animated illust), the actual image is in  ```illust.metadata.zip_urls.ugoira600x600``` and if you check the website, it supposed to have another bigger zip version (suffix with ugoira1920x1080)

**Comment by upbit** [comment]
En, may be iOS client no need 1920x1080 image, PublicAPI return the largest size pic is `image_urls .large` (pixivpy is based on iOS 5.x/6.x API)

ps: AppAPI illusts has the `meta_single_page` props, which contain the [`original_image_url`](https://github.com/upbit/pixivpy/blob/master/download_illusts.py#L33)

**Comment by Nandaka** [comment]
yep, checked ```meta_single_page.original_image_url``` but it doesn't return the zip file for ugoira.

well, I can do string replace the url and looks like it is working (should be usable with both Public API and AppAPI)

```python
image_url = json_result.illusts[0].meta_single_page.original_image_url
# https://i2.pixiv.net/img-original/img/2016/10/12/21/26/36/59440733_ugoira0.jpg
# https://i2.pixiv.net/img-zip-ugoira/img/2016/10/12/21/26/36/59440733_ugoira1920x1080.zip
ugoira = image_url.replace("img-original", "img-zip-ugoira")
ugoira = ugoira.replace("_ugoira0.jpg", "_ugoira1920x1080.zip")
aapi.download(ugoira)
```

Usually I scrape the actual page to get the urls (not using api), but looks like they now do A/B testing with new web UI to some users, and somehow I'm still get the old UI even after registering new account.
