### ISSUE TITLE
403 forbidden 

### ISSUE THREAD

**Issue by ShallJaiden** [upbit/pixivpy#190]
請問應該怎麼處理i.pxmig.net的URL呢？

**Comment by Xdynix** [comment]
添加Header `Referer: https://app-api.pixiv.net/`
[Ref](https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L165)

**Comment by ShallJaiden** [comment]
> 添加Header `Referer: https://app-api.pixiv.net/`
> [Ref](https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L165)

只能下載到本地嗎？

**Comment by Xdynix** [comment]
> > 添加Header `Referer: https://app-api.pixiv.net/`
> > [Ref](https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L165)
> 
> 只能下載到本地嗎？

是的，就是为了让其他地方没法简单地用它的图片服务器。只能绕一下，先用代码下载到本地，再给网页元素或者GUI组件或者别的什么地方。
