### ISSUE TITLE
every time I get an error when I use PixivAPI's  users_works function

### ISSUE THREAD

**Issue by yuki-2000** [upbit/pixivpy#193]
From about 1 or 2 month ago, my script has not run well, while it was good.
I search the problems and I find that when I use  users_works, 

 {'status': 'failure', 'has_error': True, 'errors': {'system': {'message': '403 Forbidden', 'code': None}}}

is returnd.
Is there anyone who has same problems? and is there a solution?

I am sorry for poor writing, but this is my first time using github issues.

**Comment by Xdynix** [comment]
Public API is being deprecrared by Pixiv. You should switch to App API (`AppPixivAPI.user_illusts()`).

**Comment by yuki-2000** [comment]
Thank you very much for quick answer.
I have to fix my complex programs...
I try to use AppPixivAPI insted of Public API.
Thank you.
