### ISSUE TITLE
Public api not working

### ISSUE THREAD

**Issue by bakashigure** [upbit/pixivpy#200]
I used the sample code from README,  the interface `search_works` returns 404, I don't know if I'm not using it the right way or something else...

my code
```python
from pixivpy3 import PixivAPI

_REQUESTS_KWARGS = {
    "proxies": {"https": "http://127.0.0.1:7890"},
}
api = PixivAPI(**_REQUESTS_KWARGS)
api.auth(refresh_token="")
json_result = api.search_works("水遊び", page=1, mode="exact_tag")
#json_result = api.ranking('illust', 'weekly', 1)
#json_result = api.users(1184799)
print(json_result)

```
![image](https://user-images.githubusercontent.com/33803916/152097871-05a91f52-bf5f-479f-92a2-b187c63c4064.png)

**Comment by Xdynix** [comment]
Public API is deprecated by Pixiv. Please use the App API (`AppPixivAPI`).

**Comment by bakashigure** [comment]
> Public API is deprecated by Pixiv. Please use the App API (`AppPixivAPI`).

原来如此，考虑从示例中移除这部分代码，或者加上`@deprecated` 标记?

**Comment by upbit** [comment]
Removed in !201

**Comment by upbit** [comment]
Removed Public-API in [v3.7.0](https://pypi.org/project/PixivPy/3.7.0/)
