### ISSUE TITLE
Drop Python<=3.6

### ISSUE THREAD

**Issue by eggplants** [upbit/pixivpy#208]
As you know, Python 2 has reached EOL in 1/1/2020. Also  Python 3.6 has reached in 23/12/2021.
I recommend to drop their versions.

**Comment by eggplants** [comment]
Please give your opinion, watchers.

**Comment by upbit** [comment]
Well, it is indeed possible to stop maintaining low versions of python.
I made a branch of `py2_final`, master will abandon python <=3.6

**Comment by eggplants** [comment]
If OK, please uncomment:

https://github.com/upbit/pixivpy/blob/735a4e7f78c698a228d08e762383364b0ad8a94b/setup.cfg#L28
