### ISSUE TITLE
default argument: type  in aapi.user_illusts() should be '' (blank), not 'illust'

### ISSUE THREAD

**Issue by yuki-2000** [upbit/pixivpy#212]
I found that in  `aapi. user_illusts()` if I set `type=''` I got both manga and illust data

I use pixivpy to download all illusts  which my following creater draw, and I use `aapi. user_illusts()` function.
looking at downloaded illusts, I found I have NO manga illusts, and I noticed there is `type` argument in this function.
Default argument is `type='illust'`, so I have to switch `type='manga'`.

However, I found if I set `type=''` I got both manga and illust data.
I suggest default type argument should be `''` (blank), or write this rule in script.

**Comment by upbit** [comment]
The reason for this is that I only paid attention to illust in the early days, so I wrote this in the parameters by default.
Modifying the default values of API parameters may cause problems in the code of users in older versions. Therefore, the recommended way is to add comments to the documentation.

Also, modifying `type=''` is not recommended. I haven't seen this kind of use on the App. If the request mode is different from the App, it will cause your request to be easily identified and banned.

**Comment by yuki-2000** [comment]
Thank you for answer.

>Modifying the default values of API parameters may cause problems in the code of users in older versions.  Therefore, the recommended way is to add comments to the documentation.

That's right. I did not think the effect on other people. 

>Also, modifying type='' is not recommended. I haven't seen this kind of use on the App. If the request mode is different from the App, it will cause your request to be easily identified and banned.

This makes sense. I have not thought get request url from thid view, so this is very helpful, and I can learn a lot from you. Thank you.

Also, I inform that `aapi. user_illusts(user_id, type=None)` can get same result as `type=""`.

Learning more, would you tell me how you analyze pixiv app(maybe ios?)'s get request or hidden api, If you do not mind.

**Comment by upbit** [comment]
Sure. I used to analyze HTTPS packets by installing Fiddler's certificate on iOS/Android. The captured request parameters can be viewed in the Wiki:

https://github.com/upbit/pixivpy/wiki/Sniffer-for-iOS-6.x---Common-API

**Comment by Xdynix** [comment]
@yuki-2000 There are many apps on iOS you can use to sniff the traffic on your phone. One I've used is Stream.
![Snipaste_2022-02-23_22-05-56](https://user-images.githubusercontent.com/14145832/155467468-5f185b80-8bd8-4d5a-9e06-f56c86ed682a.png)

**Comment by yuki-2000** [comment]
@upbit @Xdynix 
Thank you very much!
I try to learn these apps and wiki.
