### ISSUE TITLE
Annotate precise returned type of aapi.parse_qs with TypedDict

### ISSUE THREAD

**Issue by eggplants** [upbit/pixivpy#228]
Or, we use rather present type than `Optional[Dict[str, Any]]`.

---

I usually use below pattern:

```python
target_id = "..."
next_qs = {}
while next_qs is not None:
    if "user_id" not in next_qs:
        res_json = self.aapi.user_bookmarks_illust(target_id)
    else:
        res_json = self.aapi.user_bookmarks_illust(**next_qs)
    ...
    next_qs = self.aapi.parse_qs(res_json["next_url"])
```

`next_qs` is being typed as `Optional[Dict[str, str | List[str]]]` now.

But pylance reports an issue towards `**next_qs` like this:

```
Argument of type "str | List[str]" cannot be assigned to parameter "user_id" of type "int | str" in function "user_bookmarks_illust"
  Type "str | List[str]" cannot be assigned to type "int | str"
    Type "List[str]" cannot be assigned to type "int | str"
      "List[str]" is incompatible with "int"
      "List[str]" is incompatible with "str"
```

So I would like to annotate `next_qs` with TypedDict.

**Comment by upbit** [comment]
Can you provide the `next_url`, or the content/type of `next_qs`?
I verified with [`example_user_bookmarks.py`](https://github.com/upbit/pixivpy/blob/9c6ba4449c844bedf7fcb762469ef3bdbdd07750/example_user_bookmarks.py) and the output is OK:

```
❯ python -V
Python 3.7.6

❯ python example_user_bookmarks.py
[ID=93271257] 天ヶ峰蓮菜ちゃんがウェディングドレスを着たら
    https://i.pximg.net/c/600x1200_90/img-master/img/2021/10/07/00/03/23/93271257_p0_master1200.jpg
[ID=78509907] pixivファンタジア Age of Starlight
    https://i.pximg.net/c/600x1200_90/img-master/img/2020/01/06/11/41/37/78509907_p0_master1200.jpg
[ID=77277970] 対立
    https://i.pximg.net/c/600x1200_90/img-master/img/2019/10/14/00/11/51/77277970_p0_master1200.jpg
>> next_url: https://app-api.pixiv.net/v1/user/bookmarks/illust?user_id=275527&restrict=public&filter=for_ios&max_bookmark_id=3689756775
[ID=57546251] 332/365 Los Angeles
    https://i.pximg.net/c/600x1200_90/img-master/img/2016/06/23/12/20/08/57546251_p0_master1200.jpg
[ID=62499786] Path of miranda - pilot episode
    https://i.pximg.net/c/600x1200_90/img-master/img/2017/04/21/01/12/24/62499786_p0_master1200.jpg
[ID=65108010] ひらが
    https://i.pximg.net/c/600x1200_90/img-master/img/2017/09/24/03/08/31/65108010_p0_master1200.jpg
```

**Comment by eggplants** [comment]
I don't know if this is an answer, but...

Here is modified `demo.py`:
https://gist.github.com/eggplants/6cec97bd5278c45764e81813203c8b9d#file-demo_-py

I collected pairs of `next_url` and `next_qs` by each call with this:
https://gist.github.com/eggplants/6cec97bd5278c45764e81813203c8b9d#file-_

As you can see from this, each endpoint has a different key for `next_qs`.
I want to define each one as a `TypedDict` and join them in a `Union` to be the return type for `aapi.parse_qs` = `next_qs`.

If you think it is useless, I am going to stop.

**Comment by upbit** [comment]
As you can see from the output, `next_url` is various, enumerating the type of `next_qs` may be `int | str | List | Map | ...`, which is basically equivalent to `Any`.

Considering from the parameter list, it is enough to define it as `Dict[str, Any]`?
