### ISSUE TITLE
[Feature Request] 请求添加搜索热度排序 30 张预览

### ISSUE THREAD

**Issue by lazureice** [upbit/pixivpy#237]
现在的收藏数/人气排序每一页最下面的图片的收藏数其实很少，毕竟是抓完之后再排序。
有时候我只想看30张最热门的就够了。也就是官方提供的那个热度排序的预览：
`https://app-api.pixiv.net/v1/search/popular-preview/illust`

是否可以在某个地方添加一个按钮或用一个 flag 表示按热度排序？
我知道第三方 app shaft 搜索就是默认按热度排序，但我还是希望能在 PC 上看。

**Comment by Xdynix** [comment]
`pixivpy`没有GUI，只是一个模拟Pixiv手机客户端的API库，你指的是什么？

`AppPixivAPI.search_illust()`可以传入`sort="popular_desc"`来按收藏数排序，但是那需要登录的账号有订阅Pixiv会员，结果就会是先由服务器排序再返回。

**Comment by upbit** [comment]
`popular-preview`是订阅会员预览，拿不到原图的（而且只有app上看到的6张图）。正解是 @Xdynix 说的用有订阅的账号，请求 `popular` 排序结构

**Comment by lazureice** [comment]
@Xdynix 抱歉。打开的仓库有点多，加上凌晨脑子有点乱搞错仓库了……

@upbit 我用自己非会员的 token 试了下，结果是30张。虽然不能直接拿到 origin，不过 large （`https://i.pximg.net/c/600x1200_90/img-master/img/2017/04/05/00/00/02/62258773_p0_master1200.jpg`）做下字符串拼接也能得到origin。
