### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by eggplants** [upbit/pixivpy#240]
Here is diffs between v3.7.0 and current HEAD.
https://github.com/upbit/pixivpy/compare/70825f94c04df0910a37b886e3c0c36ebd2a7140..b7c857e811d3dfecd13d08893daae9cf7d036cb0

**Comment by upbit** [comment]
Hmm, I forgot to tag. I will release v3.7.1 soon

**Comment by eggplants** [comment]
> Hmm, I forgot to tag. I will release v3.7.1 soon

Following versions in PyPI have to be synced in git:

- 3.5.11
- 3.6.0
- 3.6.1
- 3.6.2
- 3.7.0

**Comment by upbit** [comment]
The update might be a bit late... I change my desktop, and lost two factor authentication application for PyPI
Currently trying to restore access to the account.

**Comment by eggplants** [comment]
https://pypi.org/help/#totp

>Note: If you lose your authentication application and can no longer log in, you may permanently lose access to your account.

>If you've lost access to all two factor methods for your account and do not have [recovery codes](https://pypi.org/help/#recoverycodes), you can request help [with account recovery](https://pypi.org/help/#account-recovery).

**Comment by upbit** [comment]
https://github.com/pypa/pypi-support/issues/1924

**Comment by upbit** [comment]
I haven't received a reply from pypi, and there are still many recovery applications in the process.

I'll think of other ways, and temporarily update it in this way:
`pip install -U git+https://github.com/upbit/pixivpy@master`

**Comment by upbit** [comment]
Currently waiting for https://github.com/pypa/pypi-support/issues/1924 to recover indefinitely

Should we create another package? like `pixivpy3` (as the current package only supports `python3`)

**Comment by upbit** [comment]
Upload to https://pypi.org/project/PixivPy3
