### ISSUE TITLE
Can I search only for non R-18(全年齢) or only for R-18?

### ISSUE THREAD

**Issue by equal-l2** [upbit/pixivpy#245]
I know the web interface of Pixiv has such options, but not sure if the API endpoint has one.

**Comment by upbit** [comment]
From the Android client, the search interface does not have a way to filter `R-18`.
If you only need `R-18` contents, you may have to filter the illusts that contain the "R-18" tag in the results.

**Comment by equal-l2** [comment]
Though it is almost not a problem in practice, "having R-18 tag" and "being mature contents" is not technically the same, because non-mature contents can have R-18 tag, and the author can remove R-18 tag from mature content while age restriction is preserved.
(very few portions of illusts are in the situation described above)

Anyway, thank you for the help!

**Comment by upbit** [comment]
You can try `tag` search, but I'm not sure if Pixiv supports multi-tag matching
