### ISSUE TITLE
有时会提示auth() failed!

### ISSUE THREAD

**Issue by lancer-wang** [upbit/pixivpy#251]
pixivpy3.utils.PixivError: [ERROR] auth() failed! check refresh_token.
HTTP 403: 
原因不明,重试之后有时候又会可以

**Comment by upbit** [comment]
如果token没问题，大概率是网络不稳定。考虑换代理或者用 example_bypass_sni.py 里的方法

**Comment by lancer-wang** [comment]
> 如果token没问题，大概率是网络不稳定。考虑换代理或者用 example_bypass_sni.py 里的方法

使用的是日本的vps,不过大概是网络不稳定,我去换个试试
