### ISSUE TITLE
How to download video? 

### ISSUE THREAD

**Issue by Honeyloy** [upbit/pixivpy#253]
How i can download video from pixiv?

**Comment by Xdynix** [comment]
What video do you mean? ugoira (animation/GIF, e.g. 102803341)?

Check the response object of illustration detail, there will be a URL for .zip file, which contains all the frames. Then calls `ugoira_metadata` and you can found the delays of each frame there.

Finally you can use libraries like Pillow to convert the frames to any format you like.

**Comment by upbit** [comment]
animation return as `ugoira` in ZIP format, just unzip it

**Comment by Honeyloy** [comment]
I find Ugoira with audio, I thought it was a normal video. 
It turns out you need to get **illust_detail** , then look at the type and if it is Ugoira then request **ugoira_detail** , get a link and **download**

**Comment by Xdynix** [comment]
Interesting, didn't know ugoira with audio before. Can you please share an illustration ID so that we can take a look?

**Comment by dfjeiwn** [comment]
Have you tried using a [YouTube downloader](https://streamfab.com/youtube-video-downloader.htm)? It supports downloading from 1000+ sites.

**Comment by Ry3yr** [comment]
> Interesting, didn't know ugoira with audio before. Can you please share an illustration ID so that we can take a look?

There are no ugoira with audio.
This request can be closed.
