### ISSUE TITLE
有什么简单的获取follwing/follower数量的办法吗?

### ISSUE THREAD

**Issue by trojblue** [upbit/pixivpy#254]
如题，现在获取粉丝量是可以登录以后用`api.user_follower(user)` 一页页爬过去数，但是粉丝量上千以后需要的请求会越来越多，有没有办法可以直接获取粉丝/关注数量？感谢。

**Comment by upbit** [comment]
我记得user_detail可以返回相关的数值

详见`user_detail的total_follower`：https://github.com/upbit/pixivpy/wiki/Sniffer-for-iOS-6.x---Common-API#%E7%94%A8%E6%88%B7---%E8%AF%A6%E6%83%85
