### ISSUE TITLE
Getting my user ID

### ISSUE THREAD

**Issue by thesadru** [upbit/pixivpy#258]
If I want to get my own bookmarks I need to provide a user ID but it seems that there is no endpoint to get info about the authenticated user directly.
The Pixiv website doesn't use an endpoint to get your own user info but rather embeds it in the main html document so that doesn't really help.

**Comment by Xdynix** [comment]
You can check the response of api.auth(). If I remember correctly it will
return your account info.

**Comment by thesadru** [comment]
Oh yes, it indeed does. Thank you!!
