### ISSUE TITLE
Cannot get correct zip URL of ugoira

### ISSUE THREAD

**Issue by Xdynix** [upbit/pixivpy#27]
If I tried to get info of an ugoira:

~~~Python
json_result = api.works(60346068)
~~~

`json_result.response[0].metadata.zip_urls.ugoira600x600` will contain an URL which link to an ZIP file. 

For example, http://i1.pixiv.net/img-zip-ugoira/img/2016/12/12/13/17/20/60346068_ugoira600x600.zip.

But this file can not be open or unzip.

If I type `pixiv.context.ugokuIllustFullscreenData.src` in web browser console, or look at HTML source code, I will get an URL link to another ZIP file, which contains all frames of the work.

The URL of right ZIP file in my example is http://i1.pixiv.net/img-zip-ugoira/img/2016/12/12/13/17/20/60346068_ugoira1920x1080.zip

It seems we can get the right URL by changing `...ugoira600x600...` to `...ugoira1920x1080...`. But I wonder if there are some more parameters should be added when fetching work information?

**Comment by upbit** [comment]
There may be a **size** like parameter to control ugoira's zip_urls in Public-API, I will check this as soon as possible.

Before you can try to use [AppAPI().user_illusts()](https://github.com/upbit/pixivpy/blob/master/demo.py#L194)  to get the ugoira's zip_urls.

**Comment by upbit** [comment]
Sorry for the late reply.

I installed Pixiv iOS/5.8.7(the newest PAPI client) and sniffer [the ugoira request](https://github.com/upbit/pixivpy/wiki/Sniffer-for-Ugoira#papi-works), no **size** like parameter found in `api.works()`.

Because the client only accesses the `600X600` zip, we may only be able to get the original zip url by replacing the `600x600` to `1920x1080`.

**Comment by Xdynix** [comment]
Thanks for your response.

This issue seems out of our control.

(I'm trying to convert the `.zip` file to `.gif` file with `PIL`, but `PIL`'s GIF module also has some issue about palette...)
