### ISSUE TITLE
吐槽

### ISSUE THREAD

**Issue by Mapaler** [upbit/pixivpy#29]
因为我做脚本的时候考虑到对于某些作品/收藏很多的人可能会中途中断获取，后面重新获取，就想做一个“断点续传”
获取作品列表时，next_url还比较好理解，offset参数就是下一页的开始位置，我直接数现在已经获取几个，下次直接offset这个数字就可以了。
但获取收藏时，那个next_url只能根据max_bookmark_id参数来定，而这个根本不知道从哪里找来。虽然papi的时候有这个id，我不可能为了这个专门去用papi。
所以最后还是得再加一个全局变量来储存next_url。

**Comment by Mapaler** [comment]
![image 3](https://cloud.githubusercontent.com/assets/6565860/21751537/c61364be-d603-11e6-93bb-8a3a46b33e85.png)
不过实际上不知道为什么，获取id:552160的收藏总是会出现一页里不足30个的情况，最后获取到的比总数少。

**Comment by Mapaler** [comment]
因为访问的链接是有“restrict=public”这一项的，所以理论上应该是能看到该用户的公共权限的收藏才对，但是还是有些不见了。
另外获取到的公共权限的收藏中，也会有一些是仅好友可见的权限，除非你刚好也是那个用户的好友，否则获取到的图片其实只是一把锁。

**Comment by upbit** [comment]
1. `next_url`：参数是在next_url里返回的，可以用`api.parse_qs()`来处理翻页；
2. 缺少的是r18作品。这些作品需要登录设置过r18可见的账户，并增加`req_auth=True`参数（因为大部分API是不需要登录的，req_auth默认为False）；

例如获取r18日榜的例子：

~~~python
api.login("username", "password")

# get ranking: 1-30 for day_r18
json_result = api.illust_ranking('day_r18', date='2017-01-07', req_auth=True)
for illust in json_result.illusts:
    print(" p1 [%s] %s" % (illust.title, illust.image_urls.medium))

# next page: 31-60
next_qs = api.parse_qs(json_result.next_url)
json_result = api.illust_ranking(req_auth=True, **next_qs)
for illust in json_result.illusts:
    print(" p2 [%s] %s" % (illust.title, illust.image_urls.medium))
~~~

**Comment by Mapaler** [comment]
我并没有使用PixivPy，因为我不会Python，我是写的JavaScript用户脚本，也没法运行Py环境，直接用的app-api自己写。
我是登陆发送了access_token了的，账号也打开了所有的年龄限制，理论上应该不会是r18不可见的原因。

我昨晚还发现，如果对方的公开收藏的**动图**对于登陆的账号是无权限状态（别人好友之间可以查看），那么获取metadate将会返回一个权限错误消息吗，还是中文的。

**Comment by upbit** [comment]
可以对比下少了哪些数据。如果是r18作品少了，一般是auth没有通过验证
没有权限访问的作品，通过API自然拿不到。返回错误码是中文，可能是pixiv识别了request里的`accept-language:zh-CN,zh`

**Comment by Mapaler** [comment]
我的程序写好了，不过目前碰到个问题，就是有个朋友想把自己的收藏按照自己的收藏Tag来储存文件，PAPI的时候，获取收藏是有Tag的，而app-api是直接获取插画数据，没有收藏Tag，请问有什么办法获取吗？

**Comment by upbit** [comment]
`user_bookmarks_illust()`是有提供tag参数的，用于过滤指定tag的收藏：

~~~py
def user_bookmarks_illust(self, user_id, restrict='public', filter='for_ios', max_bookmark_id=None, tag=None, req_auth=False):
~~~

用户收藏作品的tags列表，可以用`user_bookmark_tags_illust()`来获取
