### ISSUE TITLE
Pixiv的搜索选项中加入"是否显示AI生成作品"

### ISSUE THREAD

**Issue by xiyihan0** [upbit/pixivpy#317]
此为api调用中传递的值, 其中，search_ai_type的值若为1则显示AI生成结果，反之亦然。可以考虑在aapi中加入这个参数。
<img width="1120" alt="屏幕截图 2023-12-19 174603" src="https://github.com/upbit/pixivpy/assets/71264788/b116ce71-8578-4b2d-926c-badc16c59412">

**Comment by upbit** [comment]
目前哪些接口提供这个`search_ai_type`? search类的么？
确实可以考虑统一加下，默认值维持Pixiv的原始状态就好，也不会对以前的造成影响

**Comment by xiyihan0** [comment]
目前我捕获到的是`/v1/search/novel`和`/v1/search/illust`，确实都和search有关，稍后我会开一个PR
