### ISSUE TITLE
建议将 AppPixivAPI.illust_follow() 中的 req_auth 默认值设为 True

### ISSUE THREAD

**Issue by Wolther47** [upbit/pixivpy#32]
App 的 API 接口几乎全部都不需要登录，但是 `illust_follow()` 比较特殊，并且没有 `user_id` 传入，加之返回的同样也是字典，默认值设为 `False` 好像有些不妥

**Comment by Wolther47** [comment]
另外，PixivAPI.users_works() 中的 `include_stats` 这个参数，不论 `True` 还是 `False` 返回都没有区别

**Comment by upbit** [comment]
嗯，`illust_follow()`应该是需要鉴权的，没有设成True是个BUG

`include_stats`是iOS请求参数里的，至于作用可能Pixiv没有实现（以前PublicAPI里也有类似情况）

**Comment by upbit** [comment]
Fixed in [456ec7a](https://github.com/upbit/pixivpy/commit/456ec7ac7b25c2ecbd8d2cf70426cf2be6e80bed)

已经提交代码，将在下个版本里一起发布
