### ISSUE TITLE
Downloading R-18 images

### ISSUE THREAD

**Issue by pixivr18** [upbit/pixivpy#33]
Is this possible at all? All I'm getting is limit_r18_360.png and I can't seem to figure out how to auth and circumvent R-18 block, if that is even possible.

**Comment by upbit** [comment]
Get R-18 requires authentication, try `login()` and set `req_auth=True`, e.g:

~~~py
json_result = api.illust_ranking('day_r18', req_auth=True)
for illust in json_result.illusts:
    print(" p1 [%s] %s" % (illust.title, illust.image_urls.medium))

# next page: 31-60
next_qs = api.parse_qs(json_result.next_url)
json_result = api.illust_ranking(req_auth=True, **next_qs)
for illust in json_result.illusts:
    print(" p2 [%s] %s" % (illust.title, illust.image_urls.medium))
~~~

**Comment by pixivr18** [comment]
Is there any way to make this work with directly requesting `illust_detail()` and `download()` as well? I already have a list of image IDs I want to download.

Using it with illust_detail (`illust_detail(12345678, req_auth=True)` after a successful login() yields the same censored response as without (limit_r18-360.png for all links), and using it with download() (`download(12345678, req_auth=True)` throws a `TypeError: download() got an unexpected keyword argument 'req_auth'`.

**Comment by upbit** [comment]
If `illust_detail()` return the URL like `limit_r18-360.png`, it means you logined with a R-18 disabled account, enable it at Pixiv.net and try again.

`download()` API only accept the image URL not illust_id (and no needed req_auth=True), see the example: https://github.com/upbit/pixivpy/blob/master/download_illusts.py#L40

**Comment by pixivr18** [comment]
Oh god, yes, that was the issue. I feel stupid now for not checking this. I used this account over two years back before the API was available to download R-18, so it was definitely enabled at some point, but it must've reverted back without telling. Thank you so much, using Pixivpy is definitely easier than the spaghetti-regex I had before.
