### ISSUE TITLE
Great endpoints but images gives 403 Forbidden

### ISSUE THREAD

**Issue by apanoglu** [upbit/pixivpy#34]
Hi just using the code but returned images give 403 Forbidden error.
How to access images without getting this error.

Keep up the good work..

**Comment by steinuil** [comment]
Pixiv blocks hotlinking images, add the `Referer: https://pixiv.net` header to whatever you're using to download the images and they should be fine.

**Comment by upbit** [comment]
Correct. Pixiv check `Referer` header for all size of images, just add headers like this:

~~~
response = self.requests_call('GET', url, headers={ 'Referer': 'https://app-api.pixiv.net/' }, stream=True)
~~~

See the [download()](https://github.com/upbit/pixivpy/blob/24d7306ebfd9c6b0a93a9a9d1b423db052f5baef/pixivpy3/api.py#L114) API for detail, and the [demo](https://github.com/upbit/pixivpy/blob/master/download_illusts.py)
