### ISSUE TITLE
问题 | 请问有没有相应的api可以切换账号的r18状态

### ISSUE THREAD

**Issue by ETO-QSH** [upbit/pixivpy#369]
在我印象中，切换状态需要在网页端进行，我希望通过切换，来实现在不同时间返回不同分级的内容

**Comment by upbit** [comment]
好像没见过。客户端以前也是通过Web页面（移动端），在设置里面修改开关的

**Comment by ETO-QSH** [comment]
@upbit 好吧，感谢你的帮助！
