### ISSUE TITLE
Looking for advice about limitation of 'offset' parameter in AppPixivAPI.search_illust().

### ISSUE THREAD

**Issue by Xdynix** [upbit/pixivpy#40]
This is not an issue of `pixivpy`.

With this code

```python
from pixivpy3 import AppPixivAPI

api = AppPixivAPI()
r = api.search_illust('けものフレンズ', offset=6000)
print(r)
```

The response will be:
```python
{'error': {'message': '{"offset":["Offset must be no more than 5000"]}',
           'reason': '',
           'user_message': '',
           'user_message_details': {}}}
```

Definitely AAPI has been restricted from server-side. So it seems impossible to fetch all search result, which can be done with PAPI.

Can this be a strong evidence that PAPI is more preferable than AAPI?
Or we should try to follow up the latest API?

**Comment by upbit** [comment]
I didn't try to crawling so many data through search API, and it is also known that both PAPI and AAPI have the maximum number limitation.

If PAPI.search() work, just use it. Pixiv can't be abandoned Public-API so easy like old SAPI, because 5.x client (for iOS 8,x) depends on it :smile:

**Comment by Xdynix** [comment]
Well...It's a bit of upset to find out that upgrading my script from PAPI to AAPI is idle work.

Thank you for your advice. Next I will try to use both PAPI and AAPI together.
