### ISSUE TITLE
The illust_detail function in the App-API may have some trouble

### ISSUE THREAD

**Issue by xyqyear** [upbit/pixivpy#41]

**Comment by xyqyear** [comment]
无论是否调用login方法都是显示
`{'error': {'user_message': '', 'message': 'Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_request', 'reason': '', 'user_message_details': {}}}`

**Comment by xyqyear** [comment]
旧的API还能用，只不过那样的话我程序都得改过（懒癌限定），而且旧的api还必须要登录，APP-API不需要登录就能获取pixivid的detail

**Comment by upbit** [comment]
试了下，现在不传用户auth好像获取不到detail信息了，以前只是R-18需要
另外，好像是之前auth的方法失效了，尝登录时提示：
```json
{
    "has_error": true, 
    "errors": {
        "system": {
            "message": "104:無効なユーザーアカウントです。", 
            "code": 1508
        }
    }
}
```

我回头分析下原因

**Comment by xyqyear** [comment]
login方法返回的都是没有问题的，也有accesstoken和refreshtoken，随便试了一下添加收藏夹也是能用的，可能不是这方面的问题=w=

**Comment by upbit** [comment]
试了下，确实。login是我的帐号被封了原因
能提供下login后无法访问的`illust_id`吗？
```py
    api.login(_USERNAME, _PASSWORD)
    print(api.illust_detail(62345606, req_auth=True))
```
验证了下`62345606`正常

**Comment by xyqyear** [comment]
现在登录了就能正常获取详情了，但是还有个问题是直接访问原图的Url会403拒绝，
然后我对比了一下直接访问和跳转访问，发现从P站详情页跳转访问浏览器request的headers里多出来了：
(假如id是23406063)
`'Referer':'https://www.pixiv.net/member_illust.php?mode=medium&illust_id=23406063'`
我给加到headers里面了之后就没问题了.

**Comment by upbit** [comment]
illust_detail应该是强制要求鉴权，以前是不需要的
原图url访问时必须带Referer(但不一定是网页端这种，也可以是固定的`https://app-api.pixiv.net/`)，具体可以参考download() API的例子[download_illusts.py](https://github.com/upbit/pixivpy/blob/master/download_illusts.py)
