### ISSUE TITLE
Unable to access items in json_result

### ISSUE THREAD

**Issue by Kibouo** [upbit/pixivpy#43]
I tried executing the ``download_illusts.py`` example from the Wiki. It gave me the attached error. Same kept happening while trying other small snippets of codes from other examples listed in the README.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pixivpy3/utils.py", line 22, in __getattr__
    return self[attr]
KeyError: 'illusts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 42, in main
    for illust in json_result.illusts[:3]:
  File "/usr/lib/python3.6/site-packages/pixivpy3/utils.py", line 24, in __getattr__
    raise AttributeError(r"'JsonDict' object has no attribute '%s'" % attr)
AttributeError: 'JsonDict' object has no attribute 'illusts'
```

As you can see the ``json_result`` var doesn't contain any ``illusts``. Any idea as to why this might be?

EDIT: Just noticed a similar issue which has been closed ~7h ago from the time of writing this. It is however in Japanese which I don't understand (google translate didn't help). My apologies for the inconvenience.

**Comment by SalamanderSandwich** [comment]
Try this
`api = AppPixivAPI()
api.login(_USERNAME,_PASSWORD)
json_result = api.illust_detail(59580629,req_auth=True)
illust = json_result.illust
print(">>> origin url: %s" % illust.image_urls['large'])`

**Comment by upbit** [comment]
Please feel free to let me know if you have any question about the API :smile: 
The error shows that `json_result` may not successfully get `illusts` from Pixiv.

As @SalamanderSandwich says, Pixiv changed the behavior of `api.illust_detail()` in recent days, some API required `req_auth=Ture` to get illusts (such as R-18 rankings).

If this is the case, the `json_results` will contain the following errors:

```py
{'message': 'Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_request'}
```
