### ISSUE TITLE
How can i get all bookmarks from a user?

### ISSUE THREAD

**Issue by KurtBestor** [upbit/pixivpy#47]
I'm trying to get a list of the illusts from this page:
    https://www.pixiv.net/bookmark.php?id=14793912

Here is the code:
`api = AppPixivAPI()`
`api.login(username, password)`
`json_result = api.user_bookmarks_illust(14793912, filter=None, req_auth=True)`
`illusts = json_result.illusts`

but i got only 30 illusts. :(
Am i missing something? Any suggestions?

**Comment by upbit** [comment]
Try this, query next page by `parse_qs()`

```py
    json_result = api.user_bookmarks_illust(14793912, filter=None, req_auth=True)

    # get next page
    next_qs = aapi.parse_qs(json_result.next_url)
    json_result = aapi.user_bookmarks_illust(**next_qs)
    print(json_result)
```
