### ISSUE TITLE
Api error NoAuthorizationToken

### ISSUE THREAD

**Issue by hivemall** [upbit/pixivpy#54]
on request to https://ccx.upbit.com/api/v1/market_status/all in chromium browser i get:

{"error":{"name":"V1::Exceptions::NoAuthorizationToken","message":"로그인이 필요합니다.","dialog":"client"}}

what am i doing wrong?

**Comment by Xdynix** [comment]
Guess you are on the wrong path. `upbit.com` has nothing to do with this repo master.

**Comment by hivemall** [comment]
since you wrapped the api, you might have experienced the same. 
ok thank y

**Comment by hivemall** [comment]
oh dammit, my bad.
