### ISSUE TITLE
PAPI.users_favorite_works 返回404

### ISSUE THREAD

**Issue by journey-ad** [upbit/pixivpy#56]
**PAPI.users_favorite_works** 现在一直返回`{'status': 'failure', 'has_error': True, 'errors': {'system': {'message': '404 Not Found', 'code': None}}}`，这个接口是否已经弃用？

translate:
**PAPI.users_favorite_works** always returns `{'status': 'failure', 'has_error': True, 'errors': {'system': {'message': '404 Not Found', 'code': None}}}`, whether this interface is deprecated?

**Comment by SamusAranX** [comment]
Just ran into this issue myself, but with the `me_favorite_works` method.

**Comment by Toyaka** [comment]
the public API doesn't seems to be working

**Comment by Xdynix** [comment]
> the public API doesn't seems to be working

I have just tested that most public API endpoints work fine on my PC. Which endpoint do you think does not work?

**Comment by lovethelover** [comment]
Public-API cannot work now
Always 404 ERROR

**Comment by eggplants** [comment]
In my environment, Public API's `me_*` and `users_favorite_works` methods ain't working now...
Except them, all are fine. And App API are also fine.
People have

**Comment by eggplants** [comment]
In my environment, Public API's me_* and users_favorite_works methods ain't working now...
Except them, all are fine. And App API are also fine.
So, we have to move from Public API to App API completely, parhaps.

**Comment by Timothy-So** [comment]
Can confirm, PAPI "me_favorite_works" and "users_favorite_works" do not work. They return a 404 not found error message.

I tried switching to AAPI "user_bookmarks_illust" which works but unfortunately does not have pagination control like the above methods.

**Comment by haowen-xu** [comment]
> Can confirm, PAPI "me_favorite_works" and "users_favorite_works" do not work. They return a 404 not found error message.
> 
> I tried switching to AAPI "user_bookmarks_illust" which works but unfortunately does not have pagination control like the above methods.

It seems "max_bookmark_id" is the cure.  You may check out the "next_url" of the returned dict of "user_bookmarks_illust" to obtain this parameter.
