### ISSUE TITLE
refresh_token无法使用的问题

### ISSUE THREAD

**Issue by nisests** [upbit/pixivpy#57]
抓包对比发现使用默认的client_id和client_secret登录后返回的scope值为unlimited，如果在正常iOS APP上登录成功后scope是为空字符串的，所以可否把client_id和client_secret的设置暴露出来，因为默认值无法通过refresh_token去请求新的access_token

**Comment by upbit** [comment]
嗯，这个应该是后面版本加的。你可以把client_id和client_secret定义成全局变量，暴露个set()函数来覆盖原始值。
这个修改改了可以提交下，我来更新到repo中
