### ISSUE TITLE
如何获取一个多图作品的所有图片

### ISSUE THREAD

**Issue by NagaseYami** [upbit/pixivpy#59]
我不是很懂程序也不是很懂python，可以说是菜到不行。
所以在这里问这么蠢的问题实在是给您添麻烦了。先道个歉。

简单地说就是我参考并运行了download_illusts.py和demo.py，并且尝试获取每日排行榜的图片
但是如果只靠download_illusts.py里的代码，我发现当遇到含有多张图片的作品时，只会下载该作品的第一张图片
然后我观察了一下print输出的json，发现只有一张图的作品，和有多张图的作品，json的内容略有不同

但是upbit先生您肯定也知道有区别，所以在download_illusts.py有这么一行代码
`image_url = illust.meta_single_page.get('original_image_url', illust.image_urls.large)`

虽然因为我不太懂python所以我不知道这个get函数是哪里来的
但是可以分析出来这行代码的意思是original_image_url和illust.image_urls.large这两个二选一代入到image_url里
因为只有一张图片的作品的原画url会存放在original_image_url里，而多图作品的原画url会存放在image_urls的original里（但是当我尝试使用illust.image_urls['original']时会报错）

所以我一开始想是不是用if判断一下就能搞定，但是实际上print(illust.image_urls)告诉我这里面其实只有第一张图的各种大小的url，不管是不是多图作品
然后我就不知道该怎么办了

以上就是我个人尝试了几个小时的结果，比较傻，还请您多多见谅。
期待您的回复。

**Comment by Xdynix** [comment]
你可以通过page_count属性检查，如果发现它的页数大于1，就需要通过illust_detail()来获取详细信息，才能得到每一页的URL。illust_ranking这种会返回多个作品信息的API会省略一部分作品信息（大概是出于缩减数据量，加快传输速度的考虑吧）。

**Comment by NagaseYami** [comment]
额....Xdynix您可能产生了一些误解

首先我比较了一下illust_detail()和illust_ranking()的返回结果，基本上是相同的，只是illust_detail()只能返回一个作品，而illust_ranking()会返回一堆作品，就好像illust_ranking()的内部其实只是多次执行了illust_detail()一般（当然这只是一个比喻）
也就是说illust_ranking()在返回多个作品信息的时候并没有省略任何信息，可能是我的描述使您产生了误会。不好意思。

我的意思是，在函数返回json中，多图作品里每有一张图片json里就会有一个image_urls
但是我在写代码时，如果我写
`print(json_result.illust.image_urls)`
则只会返回该多图作品的第一张图片的image_urls
至于这个json我是用illust_detail()来获取还是用illust_ranking()来获取其实是一样的

**Comment by Xdynix** [comment]
是的，我也发现了我的错误。我比较常用PAPI（比较旧的版本）而不是AAPI，在PAPI里才需要额外获取。你可以参考这段代码。

```python
from pprint import pprint

from pixivpy3 import AppPixivAPI


def main():
    aapi = AppPixivAPI()
    aapi.login('username', 'password')

    json_result = aapi.illust_ranking('day', date='2018-07-20')  # No.6 contains multi pages

    for illust in json_result.illusts[3:6]:
        if illust.page_count == 1 and illust.type != 'ugoira':  # single page illust
            image_urls = [
                illust.meta_single_page.original_image_url
            ]
        elif illust.page_count > 1:  # multi page illust
            image_urls = [
                page.image_urls.original
                for page in illust.meta_pages
            ]
        else:  # ugoira
            image_urls = []  # AAPI will not provide download URL of ugoira. Use PAPI.

        pprint(image_urls)


if __name__ == '__main__':
    main()
```

（顺便厚颜推荐一下我的项目[PixivPixie](https://github.com/Xdynix/PixivPixie)，我在upbit先生的基础上进行了包装，使其可以更容易地访问各个作品的信息以及下载）

**Comment by NagaseYami** [comment]
感谢您的热情解答。我会参考您的代码的。
关于您的PixivPixie项目，我也会借鉴的。
再次感谢。

**Comment by upbit** [comment]
感谢 @Xdynix  #的热心解答！（顺便你的项目挂在[首页README.md](https://github.com/upbit/pixivpy/blob/master/README.md#projects-base-on-pixivpy)里了:+1:）

确实和xdynix介绍的一样，Pixiv分为单图和多图例子，多图在AAPI中通过 `illust.page_count` 来区分，多个url需要依次从`illust.meta_pages`下提取。返回的illust是个dict，可以输出(直接print)两种类型的作品，对比下json看看

**Comment by yzwik** [comment]
@Xdynix 
可以请教一下吗
我在测试aapi获取一个id的所有作品的时候，发现获取到的图片链接好像不全
比如一下id一个400多张，python终端输出就只有290张，查看了下并没有gif和视频之类的

`def get_imageUrls(pid):
    json_result = aapi.user_illusts(pid)
    while 1:
        try:
            nLen=len(json_result.illusts)
        except Exception as e:
            break
        for illust in json_result.illusts:
            if illust.page_count == 1 and illust.type != 'ugoira':  
				print(illust.meta_single_page.original_image_url)
            elif illust.page_count > 1:  
                image_urls = [
                page.image_urls.original
                for page in illust.meta_pages
                ]
                print(image_urls)
            else: 
                image_urls = []  

        try:
            next_qs = aapi.parse_qs(json_result.next_url)
            json_result = aapi.user_illusts(**next_qs)

        except Exception as e:
            break
    return 1

get_imageUrls(1566167)
`

**Comment by Xdynix** [comment]
@yzwik `user_illust()`接受一个参数`type`。这个参数的可选值是illust和manga，默认为illust，也就是说作者标记为漫画的作品不会被包含在结果里。所以你需要对这两个值分别获取一次，才能获取到这个作者的所有作品。

**Comment by yzwik** [comment]
@Xdynix 感谢回复
改成这样好像还是有十来张没拿到
比如下面这id 像67746532这组还有这张66767062都没:joy:

翻页这两句不用传类型了吧?
`next_qs = aapi.parse_qs(json_result.next_url)
 json_result = aapi.user_illusts(**next_qs)`

`
def get_imageUrls(pid,pType):
    json_result = aapi.user_illusts(pid,pType)

get_imageUrls(1566167,'illust')
get_imageUrls(1566167,'manga')
`

**Comment by Xdynix** [comment]
@yzwik 很抱歉这么晚回复。

根据我的实验，分别使用illust和manga应当可以获得这个作者（1566167）的所有作品。

这是我的实验代码，最终输出为84个作品，与网页端看到的一样。

```python
from pixivpy3 import AppPixivAPI

username = 'username'
password = 'password '

user_id = 1566167


def get_imageUrls(aapi, pid, illust_type='illust'):
    json_result = aapi.user_illusts(pid, type=illust_type)
    while 1:
        try:
            nLen = len(json_result.illusts)
        except Exception as e:
            break
        for illust in json_result.illusts:
            yield illust

            if illust.page_count == 1 and illust.type != 'ugoira':
                print(illust.meta_single_page.original_image_url)
            elif illust.page_count > 1:
                image_urls = [
                    page.image_urls.original
                    for page in illust.meta_pages
                ]
                print(image_urls)
            else:
                image_urls = []
        try:
            next_qs = aapi.parse_qs(json_result.next_url)
            json_result = aapi.user_illusts(**next_qs)
        except Exception as e:
            break
    return 1


def main():
    aapi = AppPixivAPI()
    aapi.login(username, password)

    illust_ids = set()
    for illust in get_imageUrls(aapi, user_id, 'illust'):
        illust_ids.add(illust.id)
    for illust in get_imageUrls(aapi, user_id, 'manga'):
        illust_ids.add(illust.id)

    print(len(illust_ids))


if __name__ == '__main__':
    main()
```

**Comment by yzwik** [comment]
@Xdynix 感谢这位兄台百忙之中抽空来回复我
我用了小号测了几次，结果还是少了，换常用号发现数量是对的 这难道是被官方安排了吗😂
遇到奇怪的现象 浪费您的时间了 在这里表示抱歉
`aapi.login("493377211", "qw123456")`

**Comment by Blues-star** [comment]
@Xdynix 如同楼上的问题，我用我的账号登录也发现作品少了，例如id为13992671的这个画师，web网页上显示作品数为58件，而不管是用这个包还是您给出的测试代码，返回都只有22张图片，我表示很疑惑

**Comment by Blues-star** [comment]
@Xdynix 就像楼上这样，我也遇到了类似的问题，例如画师id为13992671，网页显示的作品数为58件，而无论用api还是您的测试代码都只有22件，我表示很疑惑

**Comment by Xdynix** [comment]
@yzwik @Blues-star 这很奇怪，我这里实验结果的数量都与网页端显示的一样。

你们可以尝试一下这段代码，如果除了最终的结果数量以外，还有其它信息被打出，那可能就是发生了意料外的错误，如网络错误等。同时，还建议检查一下api登录时使用的账号设置，是否有正确设置“限制浏览的作品 (R-18)”。

```python
from pixivpy3 import AppPixivAPI

username = 'username'
password = 'password'

user_id = 13992671


def get_imageUrls(aapi, pid, illust_type='illust'):
    json_result = aapi.user_illusts(pid, type=illust_type)
    while 1:
        try:
            nLen = len(json_result.illusts)
        except Exception as e:
            print(e)

        for illust in json_result.illusts:
            yield illust

            if illust.page_count == 1 and illust.type != 'ugoira':
                # print(illust.meta_single_page.original_image_url)
                pass
            elif illust.page_count > 1:
                image_urls = [
                    page.image_urls.original
                    for page in illust.meta_pages
                ]
                # print(image_urls)
            else:
                image_urls = []

        try:
            next_qs = aapi.parse_qs(json_result.next_url)
            if next_qs is None:
                break
            json_result = aapi.user_illusts(**next_qs)
        except Exception as e:
            print(e)
            break

    return 1


def main():
    aapi = AppPixivAPI()
    aapi.login(username, password)

    illust_ids = set()
    for illust in get_imageUrls(aapi, user_id, 'illust'):
        illust_ids.add(illust.id)
    for illust in get_imageUrls(aapi, user_id, 'manga'):
        illust_ids.add(illust.id)

    print(len(illust_ids))


if __name__ == '__main__':
    main()
```

**Comment by Blues-star** [comment]
是的，的确是因为R18的设置问题导致部分图片被隐藏了，感谢你的回答。

**Comment by yzwik** [comment]
开了设置之后数量的确对了，那为啥我之前能对着网页发现哪些没有的图，而且那帐号设置打开和关闭r-18和怪诞之后，在pc端的网页浏览器去作者那里看作品数量还都是84件(关闭之后代码显示出来的是79件)

emm算了不纠结了也算是解决问题了，感谢这位大哥一直来的热心帮助 谢谢
