### ISSUE TITLE
Get json as OrderedDict

### ISSUE THREAD

**Issue by nonamethanks** [upbit/pixivpy#60]
Normally I would use "object_pairs_hook=OrderedDict" as an argument for requests.get().json() (see https://stackoverflow.com/a/35049750/9553920), but I'm not sure how to do pass that argument to AppPixivAPI methods like illust_follow().

**Comment by Xdynix** [comment]
`pixivpy` use `JsonDict` class to present Json object, which is defined in `pixivpy3/utils.py`. This class is a subclass of built-in `dict`. You can change its base class to `OrderedDict` so that the return value of all API methods will be `OrderedDict`.

Out of curiosity, why use `OrderedDict`?

**Comment by nonamethanks** [comment]
That answers my question, thanks.

And I use OrderedDict because i pass them to functions that expect that type and manipulate some of their specific properties, that's all.
