### ISSUE TITLE
这个auth的获取方法还能用吗

### ISSUE THREAD

**Issue by Rinacm** [upbit/pixivpy#61]
我这边用java写获取auth的时候给我返回了400，告诉我grant_type错误或者参数缺失，可是我用的是一样的postdata啊
喵喵喵？

**Comment by upbit** [comment]
auth的`grant_type: password`还是可以用的，看前两天跑的 demo.py 的记录正常：
https://travis-ci.org/upbit/pixivpy/builds/427745522

可以看看返回提示有没有线索，另外可以尝试换个账户试下（我之前那个usersp的账号就被ban了）

**Comment by Rinacm** [comment]
> auth的`grant_type: password`还是可以用的，看前两天跑的 demo.py 的记录正常：
> https://travis-ci.org/upbit/pixivpy/builds/427745522
> 
> 可以看看返回提示有没有线索，另外可以尝试换个账户试下（我之前那个usersp的账号就被ban了）
`String postData = "username=" + username + "&password=" + password + "&grant_type=password" + "&client_id=MOBrBDS8blbauoSck0ZfDbtuzpyT&client_secret=lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj";`
这是我的组合生成postData的代码，发过去之后java里面会报错，放浏览器里的话会返回404
我的请求链接是
`https://oauth.secure.pixiv.net/auth/token?get_secure_url=1&username={my account}&password={my password}&grant_type=password&client_id=MOBrBDS8blbauoSck0ZfDbtuzpyT&client_secret=lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj`
放在java里面运行会返回FileNotFoundException,直接在浏览器里输入的话是
`{"has_error":true,"errors":{"system":{"message":"404 Not Found","code":null}}}`
能否看一下这个是怎么回事，是我的请求链接有问题还是什么别的

**Comment by upbit** [comment]
首先，这是个POST请求，浏览器直接访问url是GET请求发过去的，不会生效
另外从你贴的URL推测，你的postData是直接拼接的？
auth接口默认接受的，是`application/x-www-form-urlencoded`的数据，需要urlencode
