### ISSUE TITLE
请问有没有什么方法可以检测图片是否完整获取?

### ISSUE THREAD

**Issue by XDcedar** [upbit/pixivpy#67]
api很好用, 非常感谢!
只是在使用download函数获取图片时偶尔会获取不完全, 目前遇到这种情况我只能人工排查, 然后重新获取..
请问有没有什么方法可以检测图片是否完整获取? 比如让download函数返回完整文件体积, 好让我能够与得到的文件比对..之类的..谢谢!

**Comment by Xdynix** [comment]
获取到图片的下载地址后，可以使用requests.header函数获得HTTP消息头，其中包含文件大小。
```python
import requests

# ...
image_url = 'https://i.pximg.net/img-original/img/2018/12/21/00/30/10/72204319_p0.png'

response = requests.head(image_url, headers={'Referer': 'https://app-api.pixiv.net/'})
content_length = int(response.headers['Content-Length'])
```

**Comment by XDcedar** [comment]
谢谢! 原来如此! 为什么会不要求登录呢? 我记得R18图需要登录才能查看..这样做也能获取R18的文件大小么?

**Comment by XDcedar** [comment]
原来是这样..谢谢解答!
