### ISSUE TITLE
访问图片 https://i.pximg.net返回403

### ISSUE THREAD

**Issue by thyukari** [upbit/pixivpy#68]
<template>
  <div>
    <a :href="src.medium" ><img :src="src.medium" width="32" height="32" /></a>
  </div>
</template>

``export default {
    name: "home",
    data () {
      return {
        src:{}
      }
    },
    mounted () {
      this.$axios.get("https://api.imjad.cn/pixiv/v2/",
        {
          params:{
            type:'illust',
            id:'72227555'
          }
        }).then(res => {
          this.src = res.data.illust.image_urls;
          console.log(this.src);
      }).catch(e => {
        console.error(e);
      })
    }
  }``
就这样，是我用错方法还是本就会403

**Comment by thyukari** [comment]
这是在vue里面写的，获取数据后将图片链接显示在img元素上，然后403了。

**Comment by Xdynix** [comment]
我通过脚本访问图片地址时都需要加上Header`'Referer': 'https://app-api.pixiv.net/'`，否则会403，不太了解前端该怎么加入请求里

**Comment by Xdynix** [comment]
可以参考这个[回答](https://stackoverflow.com/questions/23609946/img-src-path-with-header-params-to-pass)

**Comment by thyukari** [comment]
> 可以参考这个[回答](https://stackoverflow.com/questions/23609946/img-src-path-with-header-params-to-pass)

好的，谢谢

**Comment by journey-ad** [comment]
Pixiv 现在的图片服务器均配备了防盗链，访问时会验证来源(referrer)信息，前端无解
唯一的办法是用后端语言代理访问，代理时追加 referrer 值以伪造来源绕过验证

关键词：防盗链、referer
