### ISSUE TITLE
two function problem

### ISSUE THREAD

**Issue by xingoxu** [upbit/pixivpy#7]
Hello,
In base api requests_call function missing 'DELETE' handle

In pixivAPI me_favorite_works_delete function doesn't work, it returns success,but the work didn't remove from my favourites.

The following pic is what I got from the delete func.
![20151202160415](https://cloud.githubusercontent.com/assets/8542907/11526063/b587a95e-9912-11e5-9df3-63b802e78764.png)

**Comment by upbit** [comment]
抱歉，之前新增的`me_favorite_works_delete`等两个DELETE没有经过测试，只是参考之前[iOS API](https://github.com/upbit/PixivAPI_iOS/blob/32d3bedffc01ddd0b927859bbd5098c3ccee1f0e/PixivAPI/PixivAPI.m#L750) merge到了master。

我尽快抓包验证下，然后补上调用例子。

**Comment by xingoxu** [comment]
另一个delete是ok的～非常感谢回复与付出！

**Comment by upbit** [comment]
能把你的调用代码贴一下吗？ids那里实际是传单个favorite_id，不是illust_id

**Comment by xingoxu** [comment]
果然是favourite_id，是对的！

这个可以传多个id，不用一个一个传，逗号隔开

我是用c#写的。。。。
![20151202170818](https://cloud.githubusercontent.com/assets/8542907/11526712/5f0f7a7a-9917-11e5-8e9a-0bbdd5ea9c7e.png)

**Comment by upbit** [comment]
嗯。那没其他问题的话我先close掉这个issue，稍后补充调用例子到demo.py
