### ISSUE TITLE
client Id

### ISSUE THREAD

**Issue by ThePreviousOne** [upbit/pixivpy#70]
where do I go to register my own clientId and secret key? I have searched everything I can think of and followed every link I can find, but found nothing

**Comment by Xdynix** [comment]
You cannot register your own `client_id` and `client_secret`. They are used by Pixiv for its own applications. We are now using Pixiv's iOS client's `client_id` and `client_secret`. That is to say, we use them to pretend that we are iOS clients.

**Comment by Xdynix** [comment]
Ref (Chinese): http://blog.imaou.com/opensource/2014/10/09/pixiv_api_for_ios_update.html
