### ISSUE TITLE
crash in AppPixivAPI.parse_qs

### ISSUE THREAD

**Issue by ThePreviousOne** [upbit/pixivpy#71]
`    for i in range(1, 200):`
  `      for illust in json_result.illusts:`
`            if i is 1:`
`            json_result = aapi.illust_follow(req_auth=True)`
        `    else:`
    `            # get next page`
      `          next_qs = aapi.parse_qs(json_result.next_url)`
         `       json_result = aapi.illust_follow(req_auth=True, **next_qs)`

this code runs fine for the first five but then I get 
`     json_result = aapi.illust_follow(req_auth=True, **next_qs)
TypeError: illust_follow() argument after ** must be a mapping, not NoneType`

**Comment by ThePreviousOne** [comment]
I dont think its my code because it works for a bit and then crashes doing the same thing it has just done 4 times. I checked the json file, and I checked the return of parse_qs nothing seems wrong

**Comment by Xdynix** [comment]
It happens when there are no more pages. Try this:
```python
from pixivpy3 import AppPixivAPI


def main():
    aapi = AppPixivAPI()
    aapi.login('username', 'password')

    next_qs = {}
    while next_qs is not None:
        json_result = aapi.illust_follow(**next_qs)
        # do something with json_result
        next_qs = aapi.parse_qs(json_result.next_url)


if __name__ == '__main__':
    main()
```

**Comment by ThePreviousOne** [comment]
So basically it's the same as #69

**Comment by Xdynix** [comment]
Not really the same thing.

The crash in `parse_qs()` is caused by your code.
And #69 is due to the limitations of the server, we can't do anything with it.

**Comment by ThePreviousOne** [comment]
yes but my problem was that I hit the max offset (5000) for the API, on the desktop there are unlimited pages so it cant really be "that the problem. end of story"

**Comment by ThePreviousOne** [comment]
and that is the same thing

**Comment by Xdynix** [comment]
1. You should not make an assumption that you can perform the iteration for 200 times. And there is no documentation mentions that `json_result.next_url` will not become `None` after reaching the last page. Using a while loop is much more safe. This is what I said "caused by your code", they are not safe enough.

2. Even on the desktop there is still a limit on following illustrations. For regular user the limitation is 2000, and for premium user it is 5000.
