### ISSUE TITLE
无法运行demo.py

### ISSUE THREAD

**Issue by Nekoer** [upbit/pixivpy#74]
![82SL85BLYI NU )TG`JTSW](https://user-images.githubusercontent.com/32485369/56858676-bac2cd00-69b0-11e9-9c5b-d4663f413385.jpg)

在win7上运行的，python3

**Comment by Xdynix** [comment]
Pixiv被墙。在开启相应科技后，修改
```python
_REQUESTS_KWARGS = {
  # 'proxies': {
  #   'https': 'http://127.0.0.1:1087',
  # },
  # 'verify': False,       # PAPI use https, an easy way is disable requests SSL verify
}
```
中的proxies至对应的值。

**Comment by Nekoer** [comment]
解决了，谢谢大佬。
大佬知道怎么弄成网址api吗

**Comment by Xdynix** [comment]
你是指 #73 和[example_api_proxy.py](example_api_proxy.py)？

**Comment by Nekoer** [comment]
是的大佬
类似https://api.imjad.cn/pixiv_v2.md这种的

**Comment by Xdynix** [comment]
我不是很明白你的意思。
如果是要替换API的host实现免翻，那 #73 里已经讲解了。
如果是要自己部署一个API服务或者网页服务让别人访问Pixiv，那要做的就多了，需要使用Django、Flask之类的框架开发，租一台服务器部署等。

**Comment by upbit** [comment]
#73的修改可以让API访问无需代理，但auth登录(获取`access_token`)这个会明文暴露用户名密码给代理提供方，出于安全考虑不会集成在api中。

如果你想测试，可以参考[Pixivlite登录验证](https://github.com/upbit/pixivpy/wiki/Proxy-with-PixivLite#%E7%99%BB%E5%BD%95%E9%AA%8C%E8%AF%81)这个接口，通过PixivLite.com的代理来获取。

不然还是免不了像 example_api_proxy.py 里的，先挂代理login一次
