### ISSUE TITLE
Lack of Accept-Language header means tag translations are null

### ISSUE THREAD

**Issue by Mindful** [upbit/pixivpy#76]
Hi - thank you for writing this library, it's very useful! 

However, I have one request. The APIs to fetch illustrations return dictionaries which contain (among other things) lists of tags. Something like this:

> [{'name': '诗岸', 'translated_name': None}, {'name': '女の子', 'translated_name': None}, {'name': '本家', 'translated_name': None}, {'name': '薔薇', 'translated_name': None}]

However, the `translated_tag` field is _always_ `None`. The reason is that the library never sets the `Accept-Language` header in its requests. If you set it, at least for some languages, you can get tag translations. For example, if I set it to `en-US`, I get:

> [{'name': '诗岸', 'translated_name': None}, {'name': '女の子', 'translated_name': 'girl'}, {'name': '本家', 'translated_name': 'created by the original author'}, {'name': '薔薇', 'translated_name': 'rose'}]

However, the higher level API call methods take no arguments that would allow specifying language, or manipulating the request headers at all.  For example, the `AppPixivAPI` class function to get bookmarks looks like this:
> def user_bookmarks_illust(self, user_id, restrict='public', filter='for_ios', max_bookmark_id=None, tag=None, req_auth=True):

Would it be possible to add some way to specify accepted language or manipulate headers in the higher level API calls? 

Alternatively, I can just make the changes myself and submit a pull request, but you would have to tell me _how_ you want the changes made - should a language argument be optionally passed on construction to the API objects? Should another optional argument be added to each of the individual API request methods?

**Comment by upbit** [comment]
I'm glad you found it useful, and very happy to receive your merge request.

The headers are not exposed is one of my mistakes, it is reasonable to add parameters for each API, but it may be a hard work. Maybe adding a `set_headers()` function is a better choice:

```py
    def __init__(self, **requests_kwargs):
        ...
        self.headers = {}

    # Set headers for App-API
    def set_headers(self, headers):
        self.headers = headers

    # Check auth and set BearerToken to headers
    # def no_auth_requests_call(self, method, url, headers={} ...
    def no_auth_requests_call(self, method, url, params=None, data=None, req_auth=True):
        if self.headers.get('User-Agent', None) == None and self.headers.get('user-agent', None) == None:
            # Set User-Agent if not provided
            headers['App-OS'] = 'ios'
            headers['App-OS-Version'] = '12.2'
            headers['App-Version'] = '7.6.2'
            headers['User-Agent'] = 'PixivIOSApp/7.6.2 (iOS 12.2; iPhone9,1)'
```
