### ISSUE TITLE
可以通过人气排序吗？

### ISSUE THREAD

**Issue by kiraracreams** [upbit/pixivpy#78]
![image](https://user-images.githubusercontent.com/37492417/59699680-95ba4000-9224-11e9-8466-9e9c5b8cfdf0.png)
比如sort='popular'

**Comment by Xdynix** [comment]
对于Public API，如果：
1. 你登录的账户是Premium高级会员，则可以使用`sort='popular'`。
2. 否则，就只返回20个作品。

对于App API，服务器不接受'popular'、'popularity'、'bookmark'作为search_illust接口的sort的参数，需要嗅探一下客户端到底是使用了哪个参数，我没有条件实验。

**Comment by Xdynix** [comment]
我使用的方案是将所有搜索结果都拉下来，然后在本地排序。但是有另一个限制是，App API只能获取最多5000个结果，Public API只能拉取20000个结果。

**Comment by kiraracreams** [comment]
还有一个问题,我把per_page调大以后就出现了这个错误
PixivError: parse_json() error: Expecting value: line 1 column 1 (char 0)

**Comment by upbit** [comment]
PAPI的话可以把返回的json打出来看看。高概率是一个错误提示，导致`parse_json`解析失败了

**Comment by kiraracreams** [comment]
谢谢泥萌~

**Comment by kiraracreams** [comment]
我还有最后一个问题，就是search_works()不能筛选一般向和r18吗

**Comment by upbit** [comment]
首先R18有个开关，要页面设置后接口才能取到。目前还没有发现类似的接口参数，如果新版app带有这个功能，你可以尝试搜索`ios fiddler抓包`分析下参数名和取值。

btw: 如果你只需要R18，搜tag接口好像可以通过搜R18这个特殊标签，来实现筛选。

**Comment by upbit** [comment]
有问题欢迎随时咨询:)

**Comment by kiraracreams** [comment]
我只想要一般向的，那我在p站把r18开关关了是不是就可以只下一般得的了

**Comment by upbit** [comment]
是的，把你登录账号的开关关掉即可，所有接口都会过滤r18内容

**Comment by kiraracreams** [comment]
再次感谢~
