### ISSUE TITLE
Question about showing a Picture before Downloading it

### ISSUE THREAD

**Issue by Marly212** [upbit/pixivpy#91]
Hey,

I created a GUI with PyQt5 and was wondering if I can show the Picture in a Label or something else before I Download it?

**Comment by Xdynix** [comment]
Even if you open the Pixiv website, the brower will still download the images to local then show them to you. So no matter how, you need to download the pictures to display them.

In your use case, I assume you want to show some previews for the pictures to be downloaded.

You can get the URL of the thumbnail of the picture through this package. You can then download these thumbnails to a temporary folder (provided by the operating system, or a relative path, or even only into memory), and then display them in the GUI.

**Comment by Marly212** [comment]
> 
> 
> Even if you open the Pixiv website, the browser will still download the images to local then show them to you. So no matter how you need to download the pictures to display them.
> 
> In your use case, I assume you want to show some previews for the pictures to be downloaded.
> 
> You can get the URL of the thumbnail of the picture through this package. You can then download these thumbnails to a temporary folder (provided by the operating system, or a relative path, or even only into memory), and then display them in the GUI. By doing so, the thumbnails are smaller than the original files so it will be fast. And by using a temporary folder, you don't need to care about cleaning them.

Thanks for the answer. 

My plan is now to download the Thumbnail into the Temp folder on Windows and let it show.

My question is: Is the Thumbnail you mentioned the Picture itself or is it something else. If they are something else can you tell me how to download these Thumbnails?

**Comment by Xdynix** [comment]
> > Even if you open the Pixiv website, the browser will still download the images to local then show them to you. So no matter how you need to download the pictures to display them.
> > In your use case, I assume you want to show some previews for the pictures to be downloaded.
> > You can get the URL of the thumbnail of the picture through this package. You can then download these thumbnails to a temporary folder (provided by the operating system, or a relative path, or even only into memory), and then display them in the GUI. By doing so, the thumbnails are smaller than the original files so it will be fast. And by using a temporary folder, you don't need to care about cleaning them.
> 
> Thanks for the answer.
> 
> My plan is now to download the Thumbnail into the Temp folder on Windows and let it show.
> 
> My question is: Is the Thumbnail you mentioned the Picture itself or is it something else. If they are something else can you tell me how to download these Thumbnails?

The thumbnail I am referring to is a low resolution version of the image, provided by Pixiv.

Here is a demo about retriving the thumbnail.

```python
from pixivpy3 import AppPixivAPI


def main():
    api = AppPixivAPI()
    api.login('626860856@qq.com', 'badapple')

    json_result = api.illust_detail(76930603)

    thumbnail_url = json_result.illust.image_urls.medium
    api.download(thumbnail_url, path='tmp')  # The file is 45KB large.

    original_url = json_result.illust.meta_single_page.original_image_url
    api.download(original_url, path='download')  # The file is 266KB large.


if __name__ == '__main__':
    main()
```

**Comment by Marly212** [comment]
> 
> 
> > > Even if you open the Pixiv website, the browser will still download the images to local then show them to you. So no matter how you need to download the pictures to display them.
> > > In your use case, I assume you want to show some previews for the pictures to be downloaded.
> > > You can get the URL of the thumbnail of the picture through this package. You can then download these thumbnails to a temporary folder (provided by the operating system, or a relative path, or even only into memory), and then display them in the GUI. By doing so, the thumbnails are smaller than the original files so it will be fast. And by using a temporary folder, you don't need to care about cleaning them.
> > 
> > 
> > Thanks for the answer.
> > My plan is now to download the Thumbnail into the Temp folder on Windows and let it show.
> > My question is: Is the Thumbnail you mentioned the Picture itself or is it something else. If they are something else can you tell me how to download these Thumbnails?
> 
> The thumbnail I am referring to is a low resolution version of the image, provided by Pixiv.
> 
> Here is a demo about retriving the thumbnail.
> 
> ```python
> from pixivpy3 import AppPixivAPI
> 
> 
> def main():
>     api = AppPixivAPI()
>     api.login(email, password)
> 
>     json_result = api.illust_detail(76930603)
> 
>     thumbnail_url = json_result.illust.image_urls.medium
>     api.download(thumbnail_url, path='tmp')  # The file is 45KB large.
> 
>     original_url = json_result.illust.meta_single_page.original_image_url
>     api.download(original_url, path='download')  # The file is 266KB large.
> 
> 
> if __name__ == '__main__':
>     main()
> ```

 Thanks for the Demo I think I know what to do know.

Thanks for your time
