### ISSUE TITLE
auth接口返回400

### ISSUE THREAD

**Issue by Rinacm** [upbit/pixivpy#92]
吃饭前还好好的，吃饭后突然就变成400了
```http
POST /auth/token HTTP/1.1
Host: oauth.secure.pixiv.net
X-Client-Time: 2019-10-24T20:32:10.398123
X-Client-Hash: 6127c8d82dea196182a07c4ef31f3786
Content-Type: application/x-www-form-urlencoded
User-Agent: PixivAndroidApp/5.0.64 (Android 6.0)

username={我的邮箱}&password={我的密码}&grant_type=password&client_id=MOBrBDS8blbauoSck0ZfDbtuzpyT&client_secret=lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj&get_secure_url=1
```

返回结果:
```json
{
    "has_error": true,
    "errors": {
        "system": {
            "message": "access_denied",
            "code": 1508
        }
    }
}
```

**Comment by FujiMakoto** [comment]
Same here, started getting this error today.

```
pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
```

Username and password are correct.

**Comment by Rinacm** [comment]
> I am seeing this exact error as well



> Same here, started getting this error today.
> 
> ```
> pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
> HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
> ```
> 
> Username and password are correct.

every projects I know (include myself's) that based on this auth api have the same problem so I think it probably not my problem but api's

**Comment by FujiMakoto** [comment]
Yeah, looks like something will need to be updated to be compliant with whatever changed in the API.

Hopefully it's nothing too difficult.

**Comment by Mikubill** [comment]
验证的时候生成的X-Client-Hash和X-Client-Time不匹配，改一下local_time的格式就好啦（w
目前测试修改以后可以正常登录。

change this:
https://github.com/upbit/pixivpy/blob/0ca6d7495add5b0cf338ae623a52f2b8a1c2d11e/pixivpy3/api.py#L84
to 
```
local_time = datetime.utcnow().strftime( '%Y-%m-%dT%H:%M:%S+00:00' )
```
...then login.

**Comment by Rinacm** [comment]
> 验证的时候生成的X-Client-Hash和X-Client-Time不匹配，改一下local_time的格式就好啦（w
> 目前测试修改以后可以正常登录。
> 
> change this:
> https://github.com/upbit/pixivpy/blob/0ca6d7495add5b0cf338ae623a52f2b8a1c2d11e/pixivpy3/api.py#L84
> 
> 
> to
> ```
> local_time = datetime.utcnow().strftime( '%Y-%m-%dT%H:%M:%S+00:00' )
> ```
> 
> ...then login.

emm等于说p站重新设置了X-Client-Time的格式吗emmm，这理由还蛮汗的(x

**Comment by Rinacm** [comment]
> Yeah, looks like something will need to be updated to be compliant with whatever changed in the API.
> 
> Hopefully it's nothing too difficult.

see @Mikubill 's answer, you can change the code that generate the `local_time` to `local_time = datetime.utcnow().strftime( '%Y-%m-%dT%H:%M:%S+00:00' )` to fix this problem, I just tried it and works fine for me :D

**Comment by emesh0620** [comment]
I haven't been able to access pixiv for about 12 hours with the following error message (When started with VSCODE). Please take care of it as soon as possible.

> pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
> HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}

**Comment by upbit** [comment]
Merged #93 . Try install master from source to fix this

**Comment by Rinacm** [comment]
> I haven't been able to access pixiv for about 12 hours with the following error message (When started with VSCODE). Please take care of it as soon as possible.
> 
> > pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
> > HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}

read replies above, this problem has been solved

**Comment by upbit** [comment]
Sorry for the late reply, please update to v3.5.1 to resolve this issue.

**Comment by Rinacm** [comment]
> p139jp

说起来反编译时候是怎么解决混淆问题的...我反编译之后得到的都是一大堆混淆过的class
