### ISSUE TITLE
Login Fail

### ISSUE THREAD

**Issue by HateNoSaiShi** [upbit/pixivpy#94]
Today I used the api as usual. While login my pixiv account, error occurs which returns:
`[ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}`

I am sure that the username and password is right and account is not banned since I can login on web, and I didn't run into this problem until today.

**Comment by Mikubill** [comment]
Try install master from source to fix this.

git clone https://github.com/upbit/pixivpy.git
cd pixivpy/
pip uninstall pixivpy
pip install .

（另外建议尽快更新pypi上的版本

Today I used the api as usual. While login my pixiv account, error occurs
> which returns:
> [ERROR] auth() failed! check username and password. HTTP 400:
> {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}
>
> I am sure that the username and password is right and account is not
> banned since I can login on web, and I didn't run into this problem until
> today.
>

**Comment by Mikubill** [comment]
Try install master from source to fix this.Ref: #92

（另外建议尽快更新pypi上的版本

**Comment by HateNoSaiShi** [comment]
> Try install master from source to fix this.Ref: #92
> 
> （另外建议尽快更新pypi上的版本

Thank you for your reply and help.

**Comment by upbit** [comment]
@Mikubill 抱歉更新晚了，我尽快在pypi推送下新版本

**Comment by upbit** [comment]
Sorry for the late reply, please update to v3.5.1 to resolve this issue.
