### ISSUE TITLE
Can not login to api

### ISSUE THREAD

**Issue by NTHieu95** [upbit/pixivpy#95]
When I tried to login, it keeps appearing those message:
`pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"access_denied","code":1508}}}`
Is there something wrong with my account/client or the api itself is having something wrong?

**Comment by Xdynix** [comment]
Ref to #92

**Comment by upbit** [comment]
Sorry for the late reply, please update to v3.5.1 to resolve this issue.
