### ISSUE TITLE
How do I get a client_id and client_secret for myself?

### ISSUE THREAD

**Issue by SnowySailor** [upbit/pixivpy#98]

**Comment by upbit** [comment]
There is no way, currently using the client_id of the Android

**Comment by SnowySailor** [comment]
Okay. Is the hash_secret always the same value? Will it ever change? If it does change, how will I know what to use for the new value?

**Comment by upbit** [comment]
@DaRealFreak talk how to get it from Android pixiv 5.0.156, see https://github.com/upbit/pixivpy/issues/83#issuecomment-527163914

**Comment by Mikubill** [comment]
client_id 和 client_secret 在Android APK里面貌似是以硬编码的方式存储的，而且好多个版本都没有改变过... 估计不能自行生成的吧（
